export const copy = {
  en: {
    title: 'Journal review', subtitle: 'Stage 1 · Review prototype',
    notice: 'Synthetic review data · Read only · Not connected to your books',
    resetNotice: 'Refreshing this preview starts a new review. Notes are not saved.',
    organization: 'Review organization', alpha: 'Nile Services', beta: 'Delta Services',
    language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark',
    search: 'Search journals', from: 'From date', to: 'To date', date: 'Date', reference: 'Reference', description: 'Description',
    rentJournal: 'Period rent', journal: 'Journal', account: 'Account', code: 'Code', debit: 'Debit', credit: 'Credit',
    bank: 'Operating bank', rent: 'Rent expense', entries: 'Available sample entries',
    sampleOnly: 'Sample entries for this review only. This is not a complete account statement or an authoritative balance.',
    back: 'Back to journal', close: 'Close', open: 'Open journal',
    note: 'Review note (not saved)', customName: 'Custom bank name (optional, not saved)',
    scenario: 'Simulated account response', ready: 'Available', slow: 'Slow response', error: 'Error, then retry', missing: 'Not found', denied: 'Permission denied', empty: 'No entries',
    loading: 'Loading sample account…', errorMessage: 'Sample account could not be loaded.', retry: 'Try again',
    missingMessage: 'This sample account is not available.', deniedMessage: 'This simulated reviewer cannot read account details.',
    emptyMessage: 'No sample entries in this period.',
    scopeNotice: 'Review controls — synthetic scope and session only', endSession: 'End review session', startSession: 'Start review session', ended: 'Review session ended. Sample data and notes were cleared.',
    detail: 'Account detail', currency: 'Currency', scenarioNotice: 'These states demonstrate presentation; they do not verify database authorization.',
  },
  ar: {
    title: 'مراجعة اليومية', subtitle: 'المرحلة الأولى · نموذج للمراجعة',
    notice: 'بيانات اصطناعية للمراجعة · للقراءة فقط · غير متصل بدفاترك',
    resetNotice: 'تحديث هذه المعاينة يبدأ مراجعة جديدة. لا تُحفظ الملاحظات.',
    organization: 'منشأة المراجعة', alpha: 'خدمات النيل', beta: 'خدمات الدلتا',
    language: 'اللغة', theme: 'المظهر', light: 'فاتح', dark: 'داكن',
    search: 'بحث في القيود', from: 'من تاريخ', to: 'إلى تاريخ', date: 'التاريخ', reference: 'المرجع', description: 'البيان',
    rentJournal: 'إيجار الفترة', journal: 'القيد', account: 'الحساب', code: 'الكود', debit: 'مدين', credit: 'دائن',
    bank: 'بنك التشغيل', rent: 'مصروف الإيجار', entries: 'الحركات المتاحة في المثال',
    sampleOnly: 'حركات مثال المراجعة فقط. ليست كشف حساب كاملًا أو رصيدًا معتمدًا.',
    back: 'العودة إلى القيد', close: 'إغلاق', open: 'فتح القيد',
    note: 'ملاحظة مراجعة (غير محفوظة)', customName: 'اسم مخصص للبنك (اختياري، غير محفوظ)',
    scenario: 'استجابة الحساب المحاكية', ready: 'متاح', slow: 'استجابة بطيئة', error: 'خطأ ثم إعادة محاولة', missing: 'غير موجود', denied: 'دون صلاحية', empty: 'لا حركات',
    loading: 'جارٍ تحميل حساب المثال…', errorMessage: 'تعذر تحميل حساب المثال.', retry: 'إعادة المحاولة',
    missingMessage: 'حساب المثال غير متاح.', deniedMessage: 'المراجع في هذه المحاكاة لا يملك صلاحية قراءة تفاصيل الحساب.',
    emptyMessage: 'لا توجد حركات في المثال لهذه الفترة.',
    scopeNotice: 'أدوات المراجعة — نطاق وجلسة اصطناعيان فقط', endSession: 'إنهاء جلسة المراجعة', startSession: 'بدء جلسة المراجعة', ended: 'انتهت جلسة المراجعة. مُسحت بيانات المثال والملاحظات.',
    detail: 'تفاصيل الحساب', currency: 'العملة', scenarioNotice: 'هذه الحالات توضح العرض؛ ولا تثبت صلاحيات قاعدة البيانات.',
  },
} as const
