begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create temp table activity_ids(key text primary key,id uuid);
grant all on activity_ids to authenticated;
insert into activity_ids select 'org',id from public.organizations where name='Alpha Trading';
insert into activity_ids select 'other',id from public.organizations where name='Beta Supplies';
select set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
insert into activity_ids values
 ('cash',public.create_account((select id from activity_ids where key='org'),'Statement cash','asset','cash')),
 ('capital',public.create_account((select id from activity_ids where key='org'),'Statement capital','equity','owner_capital')),
 ('empty',public.create_account((select id from activity_ids where key='org'),'Unused statement','asset','bank')),
 ('group',public.create_account((select id from activity_ids where key='org'),'Statement group','asset','cash',p_account_role=>'group'));
do $$ declare org uuid := (select id from activity_ids where key='org'); cash uuid := (select id from activity_ids where key='cash'); capital uuid := (select id from activity_ids where key='capital'); tx uuid;
begin
 perform public.create_adjustment(org,'2026-01-01',jsonb_build_array(jsonb_build_object('account_id',cash,'side','debit','amount_minor',10000),jsonb_build_object('account_id',capital,'side','credit','amount_minor',10000)),'Opening history','Local test');
 tx := public.create_adjustment(org,'2026-01-10',jsonb_build_array(jsonb_build_object('account_id',cash,'side','debit','amount_minor',3000),jsonb_build_object('account_id',capital,'side','credit','amount_minor',3000)),'Receipt','Local test');
 insert into activity_ids values('receipt',tx);
 perform public.create_adjustment(org,'2026-01-11',jsonb_build_array(jsonb_build_object('account_id',cash,'side','credit','amount_minor',1000),jsonb_build_object('account_id',capital,'side','debit','amount_minor',1000)),'Payment','Local test');
 tx := public.create_adjustment(org,'2026-01-12',jsonb_build_array(jsonb_build_object('account_id',cash,'side','debit','amount_minor',500),jsonb_build_object('account_id',cash,'side','debit','amount_minor',200),jsonb_build_object('account_id',capital,'side','credit','amount_minor',700)),'Split receipt','Local test');
 insert into activity_ids values('split',tx);
 tx := public.create_draft_transaction(org,'adjustment','2026-01-15',jsonb_build_array(jsonb_build_object('account_id',cash,'side','debit','amount_minor',99999),jsonb_build_object('account_id',capital,'side','credit','amount_minor',99999)),p_description=>'Unposted');
 insert into activity_ids values('draft',tx);
end $$;
create temp table activity_result as select public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-10','2026-01-31',0,1) as data;
select is((select data->>'opening_minor' from activity_result),'10000','Opening includes earlier posted entries');
select is((select data->>'debit_minor' from activity_result),'3700','Full-period debit total ignores paging and draft');
select is((select data->>'credit_minor' from activity_result),'1000','Full-period credit total');
select is((select data->>'closing_minor' from activity_result),'12700','Opening + debits - credits = closing');
select is((select data->>'total' from activity_result),'4','Counts all posted entries, including multiple lines on same account');
select is((select jsonb_array_length(data->'rows') from activity_result),1,'Page size enforced');
select is((select data#>>'{rows,0,balance_minor}' from activity_result),'13000','First running balance includes opening');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-10','2026-01-31',1,1)#>>'{rows,0,balance_minor}','12000','Later page keeps preceding movement');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-10','2026-01-31',3,1)#>>'{rows,0,balance_minor}','12700','Equal-date ordering ends at full closing balance');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='capital'),'2026-01-10','2026-01-31')->>'closing_minor','-12700','Credit balances retain signed net-debit direction');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-02-01','2026-02-28')->>'opening_minor','12700','Period with no activity still has opening');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-02-01','2026-02-28')->>'closing_minor','12700','No movement carries opening forward');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='empty'))->>'opening_minor','0','Unused account has exact zero');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2025-01-01','2025-12-31')->>'closing_minor','0','Future entries excluded');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-10','2026-01-31',999,25)->'rows','[]'::jsonb,'Beyond last page is empty without losing totals');
select is(jsonb_array_length(public.read_activity_journal((select id from activity_ids where key='org'),(select id from activity_ids where key='split'))->'rows'),3,'Journal includes every split line');
select is(public.read_activity_journal((select id from activity_ids where key='org'),(select id from activity_ids where key='split'))->>'debit_minor','700','Journal debits exact');
select is(public.read_activity_journal((select id from activity_ids where key='org'),(select id from activity_ids where key='split'))->>'credit_minor','700','Journal credits reconcile');
select throws_ok(format('select public.read_activity_journal(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='draft')),'42501',null,'Draft is not a posted journal');
select throws_ok(format('select public.read_account_activity(%L,%L,%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-02-01','2026-01-01'),'22023',null,'Invalid date order rejected');
select throws_ok(format('select public.read_account_activity(%L,%L,%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-01','infinity'),'22023',null,'Infinite date rejected');
select throws_ok(format('select public.read_account_activity(%L,%L,null,null,0,101)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash')),'22023',null,'Oversized page rejected');
select throws_ok(format('select public.read_account_activity(%L,%L,null,null,-1,25)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash')),'22023',null,'Negative offset rejected');
select throws_ok(format('select public.read_account_activity(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='group')),'22023',null,'Group does not imply a direct ledger');
select public.reverse_transaction((select id from activity_ids where key='receipt'),'Correction','2026-01-20');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-10','2026-01-31')->>'closing_minor','9700','Original and reversal counted once each');
select ok(public.read_activity_journal((select id from activity_ids where key='org'),(select id from activity_ids where key='receipt'))->>'reversed_by_transaction_id' is not null,'Journal preserves reversal link');
select public.archive_account((select id from activity_ids where key='cash'));
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='cash'),'2026-01-10','2026-01-31')#>>'{account,is_archived}','true','Archived account history remains readable');
select public.create_adjustment((select id from activity_ids where key='org'),'2026-03-01',jsonb_build_array(jsonb_build_object('account_id',(select id from activity_ids where key='empty'),'side','debit','amount_minor',9007199254740993::bigint),jsonb_build_object('account_id',(select id from activity_ids where key='capital'),'side','credit','amount_minor',9007199254740993::bigint)),'Precision','Local test');
select is(public.read_account_activity((select id from activity_ids where key='org'),(select id from activity_ids where key='empty'),'2026-03-01','2026-03-31')->>'closing_minor','9007199254740993','Beyond JavaScript safe integer remains exact text');
select set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select lives_ok(format('select public.read_account_activity(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash')),'Viewer may read archived statement');
select lives_ok(format('select public.read_activity_journal(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='split')),'Viewer may inspect posted journal');
select set_config('request.jwt.claims','{"sub":"b0000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select throws_ok(format('select public.read_account_activity(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash')),'42501',null,'Foreign organization denied');
select throws_ok(format('select public.read_account_activity(%L,%L)',(select id from activity_ids where key='other'),(select id from activity_ids where key='cash')),'42501',null,'Foreign account cannot be read under authorized organization');
select throws_ok(format('select public.read_activity_journal(%L,%L)',(select id from activity_ids where key='other'),(select id from activity_ids where key='split')),'42501',null,'Foreign journal denied');
select set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.update_organization_system_role((select id from activity_ids where key='org'),'viewer',array['organization.read','accounts.read','reports.read']);
select set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select throws_ok(format('select public.read_account_activity(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash')),'42501',null,'Missing transaction access fails instead of silently returning partial balances');
select throws_ok(format('select public.read_activity_journal(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='split')),'42501',null,'Missing transaction access denies journal');
reset role;
update public.subscriptions set status='cancelled',trial_ends_at=now()-interval '1 day',current_period_end=now()-interval '1 day' where organization_id=(select id from activity_ids where key='org');
select set_config('request.jwt.claims','{"sub":"a0000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select lives_ok(format('select public.read_account_activity(%L,%L)',(select id from activity_ids where key='org'),(select id from activity_ids where key='cash')),'Expired subscription retains financial history');
select ok(not has_function_privilege('anon','public.read_account_activity(uuid,uuid,date,date,integer,integer)','EXECUTE'),'Anon cannot read account activity');
select ok(not has_function_privilege('anon','public.read_activity_journal(uuid,uuid)','EXECUTE'),'Anon cannot read journal');
select * from finish();
rollback;
