import { test, expect } from '@playwright/test'
for (const app of [{ name: 'Ledger', port: 4320, login: '/login', signup: '/signup' }, { name: 'Shop', port: 4321, login: '/auth/login', signup: '/auth/signup' }]) {
  test(`${app.name}: shared landing and auth layouts, responsive and Arabic`, async ({ page, context }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await context.addCookies([{ name: 'building-suit-locale', value: 'en', domain: '127.0.0.1', path: '/' }])
    await page.goto(`http://127.0.0.1:${app.port}${app.login}`)
    await expect(page.locator('.ls-auth-page')).toBeVisible()
    await expect(page.locator('input[type=email]')).toBeVisible()
    await expect(page.locator('.ls-auth-showcase')).toBeVisible()
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.locator('.ls-auth-showcase')).toBeHidden()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: 'Language · Theme' }).click()
    await page.getByRole('menuitemradio', { name: 'Dark', exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await page.getByRole('menuitemradio', { name: 'العربية' }).click()
    await expect(page.locator('html')).toHaveAttribute('dir', 'rtl')
    await page.goto(`http://127.0.0.1:${app.port}${app.signup}`)
    await expect(page.locator('.ls-auth-page')).toBeVisible()
    await expect(page.locator('ol[aria-label]')).toBeVisible()
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.goto(`http://127.0.0.1:${app.port}/`)
    await expect(page.locator('.ls-landing-hero')).toBeVisible()
    await expect(page.locator('#features')).toBeVisible()
    await expect(page.locator('#workflow')).toBeVisible()
    await expect(page.locator('#pricing')).toBeVisible()
    await page.screenshot({ path: `.local/screenshots/${app.name.toLowerCase()}-landing-ar.png`, fullPage: true })
    expect(errors).toEqual([])
  })
}
test('Shared table, modal dirty protection, wizard and confirmation', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await context.addCookies([{ name: 'building-suit-locale', value: 'en', domain: '127.0.0.1', path: '/' }])
  await page.goto('http://127.0.0.1:4322/components')
  await expect(page.getByRole('heading', { name: 'Shared component catalogue' })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Ledger Suit', exact: true })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search' }).fill('Shop')
  await expect(page.getByRole('cell', { name: 'Shop Suit', exact: true })).toBeVisible()
  await expect(page.getByRole('cell', { name: 'Ledger Suit', exact: true })).toHaveCount(0)
  await page.getByRole('searchbox', { name: 'Search' }).fill('')
  const ledgerRow = page.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Ledger Suit', exact: true }) })
  await ledgerRow.getByRole('checkbox').check()
  await expect(ledgerRow).toHaveAttribute('aria-selected', 'true')
  await ledgerRow.getByRole('checkbox').uncheck()
  await expect(ledgerRow).toHaveAttribute('aria-selected', 'false')
  await page.getByTestId('catalogue-add').click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('textbox', { name: 'Name' }).fill('Unsaved record')
  await page.keyboard.press('Escape')
  await expect(dialog.getByText('Discard unsaved changes?')).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(dialog.getByRole('textbox')).toHaveValue('Unsaved record')
  await page.keyboard.press('Escape')
  await dialog.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByTestId('catalogue-add')).toBeFocused()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(dialog.getByText('Confirm this example action?')).toBeVisible()
  await dialog.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Confirmed' })).toContainText('Confirmed')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('li[aria-current=step]')).toContainText('Workspace')
  await page.getByRole('button', { name: 'Previous', exact: true }).click()
  await expect(page.locator('li[aria-current=step]')).toContainText('Account')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: '.local/screenshots/shared-catalogue.png', fullPage: true })
  expect(errors).toEqual([])
})
test('Documentation is searchable and source documents render', async ({ page }) => {
  await page.goto('http://127.0.0.1:4322/')
  await page.getByRole('searchbox').fill('COLOR_SYSTEM')
  const link = page.locator('main ul a').first()
  await expect(link).toBeVisible()
  await link.click()
  await expect(page.locator('.bs-document h1')).toBeVisible()
})
