<script setup lang="ts">
import type { NotificationMenuItem } from '@building-suit/contracts'
const props = defineProps<{ items: NotificationMenuItem[]; label: string; emptyLabel: string; markAllLabel: string; pending?: boolean }>()
defineEmits<{ select: [id: string]; 'mark-all': [] }>()
const open = ref(false)
const root = ref<HTMLElement | null>(null)
useClickOutside(root, () => { open.value = false })
const unread = computed(() => props.items.filter(item => !item.read).length)
</script>
<template><div ref="root" class="bs-notification-menu"><BsButton type="button" variant="icon" :aria-label="label" :aria-expanded="open" aria-haspopup="menu" @click="open = !open"><BsIcon name="notification" /><span v-if="unread" class="bs-notification-menu__badge">{{ unread }}</span></BsButton><div v-if="open" class="bs-notification-menu__panel" role="menu"><header><h2>{{ label }}</h2><BsButton v-if="unread" variant="link" size="sm" :pending="pending" @click="$emit('mark-all')">{{ markAllLabel }}</BsButton></header><BsStateSurface v-if="!items.length" state="empty" :title="emptyLabel" compact /><BsButton v-for="item in items" v-else :key="item.id" variant="text" class="bs-notification-menu__item" :data-unread="!item.read || undefined" role="menuitem" @click="$emit('select', item.id)"><span>{{ item.title }}</span><small v-if="item.body">{{ item.body }}</small><time v-if="item.timestamp">{{ item.timestamp }}</time></BsButton></div></div></template>
<style>.bs-notification-menu { position: relative; }.bs-notification-menu__badge { position: absolute; inset-block-start: -.25rem; inset-inline-end: -.25rem; display: grid; min-width: 1.1rem; height: 1.1rem; padding-inline: .2rem; place-items: center; border-radius: 999px; background: var(--bs-status-error); color: white; font-size: .65rem; }.bs-notification-menu__panel { position: absolute; z-index: 40; inset-inline-end: 0; width: min(24rem, calc(100vw - 2rem)); margin-top: var(--bs-space-1); padding: var(--bs-space-2); border: 1px solid var(--bs-border); border-radius: var(--bs-radius-card); background: var(--bs-surface); box-shadow: var(--bs-elevation-overlay); }.bs-notification-menu__panel header { display: flex; align-items: center; justify-content: space-between; padding: var(--bs-space-2); }.bs-notification-menu__panel h2 { font-weight: var(--bs-weight-bold); }.bs-notification-menu__item { display: grid !important; width: 100%; justify-items: start; padding: var(--bs-space-2) var(--bs-space-3) !important; text-align: start; }.bs-notification-menu__item[data-unread] { background: var(--bs-surface-muted); }.bs-notification-menu__item span { font-weight: var(--bs-weight-semibold); }.bs-notification-menu__item small, .bs-notification-menu__item time { color: var(--bs-text-muted); font-size: var(--bs-type-caption-size); }</style>
