<script setup lang="ts">
import type { RetryPolicyRow } from '../../types/operations'
const { data, error, refresh } = await useFetch<{ policies: RetryPolicyRow[] }>('/api/policies')
const { data: operator } = await useFetch<{ writesEnabled: boolean }>('/api/operator/status')
const form = reactive({ policy_id: '', display_name: '', max_attempts: 3, attempt_profiles: 'standard,standard,deep', active: true })
const feedback = ref('')
function edit(policy: RetryPolicyRow) { Object.assign(form, { policy_id: policy.policy_id, display_name: policy.display_name, max_attempts: policy.max_attempts, attempt_profiles: policy.attempt_profiles.join(','), active: policy.active }); feedback.value = '' }
async function save() {
  feedback.value = ''
  const profiles = form.attempt_profiles.split(',').map(value => value.trim()).filter(Boolean)
  if (profiles.length !== form.max_attempts) { feedback.value = `Expected ${form.max_attempts} profiles; received ${profiles.length}.`; return }
  try { await $fetch('/api/operator/policies', { method: 'POST', body: { ...form, attempt_profiles: profiles, metadata: {} } }); feedback.value = 'Policy saved and audited.'; await refresh() }
  catch (cause) { feedback.value = cause instanceof Error ? cause.message : String(cause) }
}
</script>
<template><main class="space-y-5"><div><p class="text-xs font-bold uppercase tracking-widest text-fg-muted">Routing</p><h1 class="mt-2 text-3xl font-black">Retry policies</h1><p class="mt-1 text-sm text-fg-muted">Every attempt has an explicit profile. Assignments inherit global → project → workstream → task.</p></div><section class="rounded-card border border-[var(--bs-border)] bg-surface p-5"><h2 class="font-black">Create or edit policy</h2><div class="mt-3 grid gap-3 md:grid-cols-3"><label class="text-xs font-bold text-fg-muted">Policy ID<input v-model="form.policy_id" class="mt-1 w-full rounded-control border border-[var(--bs-border)] bg-background px-3 py-2 text-sm text-fg"></label><label class="text-xs font-bold text-fg-muted">Display name<input v-model="form.display_name" class="mt-1 w-full rounded-control border border-[var(--bs-border)] bg-background px-3 py-2 text-sm text-fg"></label><label class="text-xs font-bold text-fg-muted">Max attempts<input v-model.number="form.max_attempts" type="number" min="1" max="20" class="mt-1 w-full rounded-control border border-[var(--bs-border)] bg-background px-3 py-2 text-sm text-fg"></label></div><label class="mt-3 block text-xs font-bold text-fg-muted">Attempt profiles, comma-separated<input v-model="form.attempt_profiles" class="mt-1 w-full rounded-control border border-[var(--bs-border)] bg-background px-3 py-2 font-mono text-sm text-fg"></label><div class="mt-3 flex flex-wrap items-center gap-2"><label class="flex items-center gap-2 text-sm"><input v-model="form.active" type="checkbox">Active</label><button :disabled="!operator?.writesEnabled" class="rounded-control bg-primary px-3 py-2 text-sm font-bold text-primary-contrast disabled:opacity-50" @click="save">Validate and save</button><span class="text-xs text-fg-muted">{{ operator?.writesEnabled ? 'Operator writes enabled' : 'Configure NUXT_CONTROL_OPERATOR_DATABASE_URL to save' }}</span></div><p v-if="feedback" class="mt-3 rounded-control bg-background p-3 text-sm">{{ feedback }}</p></section><p v-if="error" class="text-danger">{{ error.message }}</p><div class="grid gap-4 xl:grid-cols-2"><article v-for="policy in data?.policies || []" :key="policy.policy_id" class="rounded-card border border-[var(--bs-border)] bg-surface p-5"><div class="flex justify-between gap-3"><div><h2 class="font-black">{{ policy.display_name }}</h2><p class="font-mono text-xs text-fg-muted">{{ policy.policy_id }}</p></div><div class="flex items-start gap-2"><DashboardStatusPill :value="policy.active ? 'active' : 'inactive'" /><button class="text-xs font-bold text-link" @click="edit(policy)">Edit</button></div></div><ol class="mt-4 grid gap-2 sm:grid-cols-2"><li v-for="(profile,index) in policy.attempt_profiles" :key="index" class="rounded-control border border-[var(--bs-border)] p-3 text-sm"><span class="text-fg-muted">Attempt {{ index + 1 }}</span><strong class="ms-2">{{ profile }}</strong></li></ol></article></div></main></template>
