import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const checks = [];

function ok(name, condition) {
  checks.push({ name, condition: Boolean(condition) });
}

function read(path) {
  return readFileSync(join(root, path), "utf8");
}

function walk(dir, out = []) {
  for (const item of readdirSync(join(root, dir))) {
    if (["node_modules", ".vite"].includes(item)) continue;
    const rel = join(dir, item);
    const abs = join(root, rel);
    const stat = statSync(abs);
    if (stat.isDirectory()) walk(rel, out);
    else out.push(rel);
  }
  return out;
}

const pkg = JSON.parse(read("package.json"));
const app = read("src/App.js");
const authIcon = read("src/components/AuthIcon.js");
const styles = read("src/styles.css");
const files = walk(".");
const textFiles = files.filter(
  (file) => /\.(js|css|html|json|mjs)$/.test(file) && file !== "scripts/check.mjs"
);
const combined = textFiles.map((file) => read(file)).join("\n");
const spacingScale = new Set(["0", "4", "8", "12", "16", "24", "32", "48", "64", "96"]);
const spacingMatches = [...styles.matchAll(/^\s*(gap|padding(?:-[a-z]+)*|margin(?:-[a-z]+)*):\s*([^;]+);/gm)];
const offScaleSpacing = spacingMatches.filter(([, , value]) => {
  const pxValues = [...value.matchAll(/-?(\d+)px/g)].map((match) => match[1]);
  return pxValues.some((size) => !spacingScale.has(size));
});
const buttonRadiusRules = [
  /\.auth-switchers button\s*\{[\s\S]*?border-radius:\s*var\(--bs-radius-button\);/,
  /\.button\s*\{[\s\S]*?border-radius:\s*var\(--bs-radius-button\);/,
  /\.icon-button\s*\{[\s\S]*?border-radius:\s*var\(--bs-radius-button\);/,
  /\.field-icon-button\s*\{[\s\S]*?border-radius:\s*var\(--bs-radius-button\);/
];

ok("package uses Vue", Boolean(pkg.dependencies?.vue));
ok("package uses Vite", Boolean(pkg.devDependencies?.vite));
ok("package uses Hugeicons Vue renderer", Boolean(pkg.dependencies?.["@hugeicons/vue"]));
ok("package uses Hugeicons free icon data", Boolean(pkg.dependencies?.["@hugeicons/core-free-icons"]));
ok("package no longer depends on Pug", !JSON.stringify(pkg).includes("pug"));
ok("React is not installed", !JSON.stringify(pkg).toLowerCase().includes("react"));
ok("auth-html-css folder removed", !existsSync(join(root, "auth-html-css")));
ok("old Pug folder removed", !existsSync(join(root, "pug")));
ok("old source-css folder removed", !existsSync(join(root, "src/css")));
ok("old standalone dist is regenerated by Vite", existsSync(join(root, "dist/index.html")));
ok("logo assets live in public", existsSync(join(root, "public/assets/logos/building-suit-logo-light.png")));
ok("shared auth screen component is used", app.includes("<AuthScreen"));
ok("shared floating field component is used", app.includes("<FloatingField"));
ok("language and color mode switchers are in Vue", app.includes("<ViewSwitchers"));
ok("every auth screen uses shared switchers", (app.match(/<ViewSwitchers/g) || []).length === 7);
ok("actual Google mark component is used", app.includes("<GoogleMark"));
ok("forgot password text preserved", app.includes("forgot password?"));
ok("brand lockup uses logo-adjacent uilding Suit", app.includes("uilding Suit"));
ok("brand lockup text uses Display token and end alignment", /\.brand-mark\s*\{[\s\S]*?align-items:\s*end;[\s\S]*?font-size:\s*var\(--bs-type-display-size\);[\s\S]*?line-height:\s*var\(--bs-type-display-lh\);[\s\S]*?font-weight:\s*var\(--bs-weight-extrabold\);/.test(styles));
ok("outlined floating label behavior exists", styles.includes(".floating-field:focus-within .field-label"));
ok("brand input height token is preserved", styles.includes("--bs-input-height: 48px") && styles.includes("min-height: var(--bs-input-height)"));
ok("brand input radius token is preserved", styles.includes("--bs-radius-input: 12px") && styles.includes("border-radius: var(--bs-radius-input)"));
ok("spacing uses the 8px token scale", offScaleSpacing.length === 0);
ok("auth form gap uses token scale", styles.includes(".auth-form {\n  display: grid;\n  gap: 16px;") && !styles.includes("gap: 15px"));
ok("buttons use 12px brand radius, not pill radius", buttonRadiusRules.every((rule) => rule.test(styles)));
ok("reference design-system tokens are present", styles.includes("--bs-font-latin") && styles.includes("--bs-button-height: 48px") && styles.includes("--bs-motion-quick: 120ms ease"));
ok("focus ring uses Premium Gold, not Gold 700", styles.includes("--bs-focus-ring: var(--bs-premium-gold)") && !/focus-ring:\s*var\(--bs-gold-700\)|focus-ring:\s*#a86c1c/i.test(styles));
ok("dark primary action flips to Premium Gold", styles.includes("--bs-primary: var(--bs-premium-gold)") && styles.includes("background: var(--bs-primary)"));
ok("light text token uses Graphite Text", styles.includes("--bs-text: var(--bs-graphite-text)") && styles.includes("--bs-graphite-text: #232b33"));
ok("button primitive matches design-system reference", styles.includes("padding: var(--bs-space-3) var(--bs-space-5)") && styles.includes("box-shadow: var(--bs-elevation-1)") && styles.includes("font-weight: var(--bs-weight-semibold)"));
ok("input primitive matches design-system reference except floating label", styles.includes("border: 1.5px solid var(--bs-border)") && styles.includes("box-shadow: 0 0 0 3px rgba(216, 155, 66, 0.15)") && styles.includes("font-size: var(--bs-type-body-m-size)"));
ok("semantic colors are not decorative auth hero washes", !/rgba\(46,\s*158,\s*107|rgba\(47,\s*119,\s*201|rgba\(209,\s*75,\s*75/.test(styles));
ok("RTL keeps brand lockup LTR", styles.includes("[dir=\"rtl\"] .brand-mark"));
ok("app icons render through Hugeicons", authIcon.includes("@hugeicons/vue") && authIcon.includes("@hugeicons/core-free-icons"));
ok("no local app icon SVG path map remains", !authIcon.includes("iconPaths") && !authIcon.includes("v-html"));
ok("old portal subtitle removed", !combined.includes("Private building portal"));
ok("old forgot label removed", !combined.includes("Forgot?"));
ok("CSS-drawn fingerprint removed", !combined.includes("fingerprint-icon"));
ok("old Pug generated class duplication absent", !combined.includes("bs-btn bs-btn"));

const failed = checks.filter((check) => !check.condition);
for (const check of checks) {
  console.log(`${check.condition ? "PASS" : "FAIL"}  ${check.name}`);
}

if (failed.length) {
  console.error(`\n${failed.length} failed, ${checks.length - failed.length} passed.`);
  process.exit(1);
}

console.log(`\n${checks.length} passed, 0 failed.`);
