// Generated by scripts/test-dashboard-performance-embedded.mjs --generate-contract.
// Source: migrated PostgreSQL catalog. Do not edit.
import type { Database, Json } from './database.types'

export type AccountsReportsRpcDatabase = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
    Functions: {
      read_account_balances: {
        Args: { p_organization_id: string }
        Returns: {
          organization_id: string
          account_id: string
          code: string | null
          name: string
          type: Database['public']['Enums']['account_type']
          subtype: Database['public']['Enums']['account_subtype']
          currency: string
          account_role: string
          control_subledger_type: Database['public']['Enums']['control_subledger_type'] | null
          control_binding_locked: boolean
          normal_balance: Database['public']['Enums']['normal_balance']
          contra_account_id: string | null
          is_system: boolean
          classification_locked: boolean
          net_debit_minor: string
          statement_balance_minor: string
          entry_count: number
          is_archived: boolean
          is_liquid: boolean
          parent_account_id: string | null
        }[]
      }
      report_financial_overview: {
        Args: {
          p_organization_id: string
          p_from_date: string
          p_to_date: string
          p_as_of_date?: string
        }
        Returns: Json
      }
    }
  }
}
