// Generated by scripts/generate-ap-contracts.mjs from the migrated PostgreSQL catalog.
// Bigint accepts decimal strings to preserve exact PostgREST transport. Do not edit.
import type { Json } from './database.types'

export type ApRpcDatabase = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: {
    post_ap_document: {
      Args: {
        p_organization_id: string
        p_kind: string
        p_supplier_id: string
        p_control_account_id: string
        p_document_date: string
        p_amount_minor: string | number
        p_offset_account_id: string
        p_reference: string
        p_idempotency_key: string
        p_due_date?: string | null
        p_allocations?: Json | null
        p_reason?: string | null
        p_reverses_document_id?: string | null
      }
      Returns: string
    }
    preview_legacy_ap: {
      Args: {
        p_organization_id: string
      }
      Returns: {
        commitment_id: string
        supplier_id: string
        reference: string
        currency_code: string
        original_minor: string
        cash_settled_minor: string
        legacy_open_minor: string
        linked_account_id: string
        treatment: string
      }[]
    }
    read_ap_open_items: {
      Args: {
        p_organization_id: string
        p_as_of_date: string
        p_supplier_id?: string | null
      }
      Returns: {
        bill_id: string
        supplier_id: string
        supplier_name: string
        control_account_id: string
        reference: string
        issue_date: string
        due_date: string
        original_minor: string
        outstanding_minor: string
        aging_bucket: string
      }[]
    }
    read_ap_statement: {
      Args: {
        p_organization_id: string
        p_supplier_id: string
        p_from: string
        p_to: string
      }
      Returns: Json
    }
    read_ap_workspace: {
      Args: {
        p_organization_id: string
        p_as_of_date: string
        p_from: string
        p_supplier_id?: string | null
      }
      Returns: Json
    }
    reverse_ap_document: {
      Args: {
        p_organization_id: string
        p_document_id: string
        p_date: string
        p_reason: string
        p_idempotency_key: string
      }
      Returns: string
    }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
