// Generated by scripts/test-dashboard-performance-embedded.mjs --generate-contract.
// Source: migrated PostgreSQL catalog. Do not edit.
import type { Database } from './database.types'

export type DashboardRpcDatabase = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
    Functions: {
      dashboard_liquid_accounts: {
        Args: {
          p_organization_id: string
        }
        Returns: {
          account_id: string
          name: string
          currency: string
          net_debit_minor: string
          subtype: Database['public']['Enums']['account_subtype']
        }[]
      }
    }
  }
}
