// Generated by scripts/test-manual-payment-embedded.mjs --generate-contract.
// Source: migrated PostgreSQL catalog. Do not edit.

export type ManualPaymentRequest = {
  id: string
  organization_id: string
  created_by: string
  plan_id: string
  plan_key: string
  price_id: string
  billing_interval: 'monthly' | 'yearly'
  amount_minor: number
  currency_code: string
  instructions: string
  status: string
  evidence_id: string | null
  created_at: string
  period_start: string | null
  period_end: string | null
}

export type ManualPaymentEvidence = {
  id: string
  request_id: string
  organization_id: string
  object_id: string
  storage_key: string
  filename: string
  mime_type: string
  size_bytes: number
  sha256: string
  submitted_by: string
  submitted_at: string
}

export type ManualPaymentHistory = {
  id: string
  request_id: string
  organization_id: string
  evidence_id: string | null
  actor_id: string
  reason: string
  before_state: string | null
  after_state: string
  occurred_at: string
}

type ReadTable<Row> = { Row: Row, Insert: never, Update: never, Relationships: [] }
export type ManualPaymentDatabase = { public: {
  Tables: {
    manual_payment_requests: ReadTable<ManualPaymentRequest>
    manual_payment_evidence: ReadTable<ManualPaymentEvidence>
    manual_payment_history: ReadTable<ManualPaymentHistory>
  }
  Views: Record<string, never>
  Enums: Record<string, never>
  CompositeTypes: Record<string, never>
  Functions: {
    prepare_manual_payment: { Args: { p_id: string, p_organization_id: string, p_plan_key: string, p_interval: 'monthly' | 'yearly' }, Returns: ManualPaymentRequest }
    cancel_manual_payment: { Args: { p_request_id: string, p_reason: string }, Returns: ManualPaymentRequest }
  }
} }
