// Generated by scripts/test-manual-payment-embedded.mjs --generate-admin-contract.
// Source: migrated PostgreSQL catalog. Do not edit.
import type { Json } from './database.types'

export type PlatformAdminDatabase = { public: {
  Tables: Record<string, never>
  Views: Record<string, never>
  Enums: Record<string, never>
  CompositeTypes: Record<string, never>
  Functions: {
    platform_admin_read: { Args: { p_resource: string, p_offset?: number, p_limit?: number, p_target_id?: string }, Returns: Json }
    platform_admin_review_payment: { Args: { p_command_id: string, p_request_id: string, p_evidence_id: string, p_action: string, p_reason: string, p_context: string }, Returns: Json }
  }
} }
