-- Level 0: current identities/lifecycle only. Evidence stays on the server.
WITH active_runs AS (
 SELECT r.run_id,r.project_id,r.workstream_slug,r.status,r.current_task_id,r.completed_tasks,r.max_tasks,r.finished_at,r.started_at,r.updated_at,r.stop_requested,r.maintenance_requested,r.controller_lease_token,r.controller_lease_expires_at,r.admitted_repair_id FROM control.workflow_runs r WHERE control.run_is_actionable(r.status,r.current_task_id,r.finished_at)
), subjects AS (
 SELECT 'run:'||r.run_id key,jsonb_build_object('run_id',r.run_id,'project_id',r.project_id,'workstream_slug',r.workstream_slug,'status',r.status,'current_task_id',r.current_task_id,'completed_tasks',r.completed_tasks,'max_tasks',r.max_tasks,'finished_at',r.finished_at,'started_at',r.started_at,'updated_at',r.updated_at,'stop_requested',r.stop_requested,'maintenance_requested',r.maintenance_requested,'controller_lease_token',r.controller_lease_token,'controller_lease_expires_at',r.controller_lease_expires_at,'admitted_repair_id',r.admitted_repair_id) run,t.task_id FROM active_runs r LEFT JOIN control.tasks t ON t.task_id=r.current_task_id
 UNION ALL
 SELECT 'task:'||t.task_id,NULL::jsonb,t.task_id FROM control.tasks t WHERE status IN('in_progress','verification','passed','failed')
 AND NOT EXISTS(SELECT 1 FROM active_runs r WHERE r.current_task_id=t.task_id)
)
SELECT coalesce(jsonb_agg(jsonb_build_object('key',s.key,'run',s.run,'task',CASE WHEN t.task_id IS NOT NULL THEN jsonb_build_object('task_id',t.task_id,'workstream_slug',t.workstream_slug,'suit_slug',t.suit_slug,'status',t.status,'updated_at',t.updated_at,'model_profile',t.model_profile) END,'execution',e.data,'verification',v.data,'recovery',rec.data,'operation',op.data,'publication',pub.data,'publication_started',(SELECT jsonb_build_object('at',ev.created_at,'operation_id',ev.payload->>'operation_id') FROM control.task_events ev WHERE ev.task_id=t.task_id AND ev.event_type='publication_started' ORDER BY event_id DESC LIMIT 1),
 'gate_status',gates.data,
 'admission',admission.data,
 'approved_incident',approved.data,
 'policy',jsonb_build_object('max_attempts',control.resolved_retry_policy(t.task_id)->'max_attempts'),
 'accounting',accounting.data,
 'last_progress_at',progress.created_at,'latest_event_id',progress.event_id,'incident_recovery',(SELECT jsonb_build_object('incident_id',j.incident_id,'owner',j.owner,'action',j.action,'status',j.status,'started_at',j.started_at,'next_check_at',j.next_check_at,'attempts',j.attempts,'claim_until',j.claim_until)||jsonb_build_object('generation',incident.recovery_generation,'evidence',jsonb_build_object('reason',left(j.evidence->>'reason',500))) FROM control.dot_recovery_jobs j JOIN control.dot_incidents incident USING(incident_id) WHERE j.run_id=(s.run->>'run_id')::uuid AND j.task_id IS NOT DISTINCT FROM t.task_id AND j.status IN('queued','running','human-gate') ORDER BY (j.status='running' AND j.claim_until>now()) DESC,EXISTS(SELECT 1 FROM control.operator_invocation_extensions g WHERE g.incident_id=j.incident_id AND g.kind='incident-investigation-extension' AND g.revoked_at IS NULL AND g.consumed_at IS NULL AND g.granted_at>now()-interval '45 minutes') DESC,started_at DESC LIMIT 1),
 'bounded_scope_exhausted',s.run IS NOT NULL AND (EXISTS(SELECT 1 FROM control.dot_task_scope_authorities a WHERE a.run_id=(s.run->>'run_id')::uuid) OR EXISTS(SELECT 1 FROM control.batch_task_admissions a WHERE a.run_id=(s.run->>'run_id')::uuid))
 AND NOT EXISTS(SELECT 1 FROM control.tasks candidate WHERE candidate.status NOT IN('complete','cancelled') AND (EXISTS(SELECT 1 FROM control.dot_task_scope_authorities a WHERE a.run_id=(s.run->>'run_id')::uuid AND a.task_id=candidate.task_id) OR EXISTS(SELECT 1 FROM control.batch_task_admissions a WHERE a.run_id=(s.run->>'run_id')::uuid AND a.task_id=candidate.task_id))),
 'unowned_prerequisite',(SELECT parent.task_id FROM control.tasks candidate JOIN control.task_dependencies d ON d.task_id=candidate.task_id AND d.dependency_type='hard' JOIN control.tasks parent ON parent.task_id=d.depends_on_task_id AND parent.status<>'complete'
 WHERE candidate.status NOT IN('complete','cancelled') AND (EXISTS(SELECT 1 FROM control.dot_task_scope_authorities a WHERE a.run_id=(s.run->>'run_id')::uuid AND a.task_id=candidate.task_id) OR EXISTS(SELECT 1 FROM control.batch_task_admissions a WHERE a.run_id=(s.run->>'run_id')::uuid AND a.task_id=candidate.task_id))
 AND NOT EXISTS(SELECT 1 FROM control.workflow_runs owner WHERE owner.status='running' AND (owner.current_task_id=parent.task_id OR EXISTS(SELECT 1 FROM control.dot_task_scope_authorities a WHERE a.run_id=owner.run_id AND a.task_id=parent.task_id) OR EXISTS(SELECT 1 FROM control.batch_task_admissions a WHERE a.run_id=owner.run_id AND a.task_id=parent.task_id AND a.status='admitted')))
 ORDER BY candidate.sequence,parent.task_id LIMIT 1),
 'blocking_dependency',EXISTS(SELECT 1 FROM control.task_dependencies d JOIN control.tasks parent ON parent.task_id=d.depends_on_task_id WHERE d.task_id=t.task_id AND d.dependency_type='hard' AND parent.status<>'complete'),
 'blocking_decision',EXISTS(SELECT 1 FROM control.task_decisions td JOIN control.decisions d ON d.suit_slug=td.suit_slug AND d.decision_id=td.decision_id WHERE td.task_id=t.task_id AND td.blocking AND d.status<>'approved'),
 'next_eligible_task',(SELECT ready.task_id FROM control.ready_tasks ready WHERE ready.project_id=(s.run->>'project_id')::uuid AND ready.workstream_slug=s.run->>'workstream_slug'
 AND (EXISTS(SELECT 1 FROM control.dot_task_scope_authorities a WHERE a.run_id=(s.run->>'run_id')::uuid AND a.task_id=ready.task_id)
 OR EXISTS(SELECT 1 FROM control.batch_task_admissions a WHERE a.run_id=(s.run->>'run_id')::uuid AND a.task_id=ready.task_id AND a.status='admitted')) ORDER BY ready.priority,ready.sequence LIMIT 1)
)),'[]'::jsonb)
FROM subjects s LEFT JOIN control.tasks t ON t.task_id=s.task_id
LEFT JOIN LATERAL(SELECT jsonb_build_object('execution_id',e.execution_id,'task_id',e.task_id,'attempt',e.attempt,'status',e.status,'model_name',e.model_name,'model_profile',e.model_profile,'reasoning_effort',e.reasoning_effort,'worktree_path',e.worktree_path,'started_at',e.started_at,'finished_at',e.finished_at) data FROM control.executions e WHERE e.task_id=t.task_id ORDER BY attempt DESC,execution_id DESC LIMIT 1)e ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('verification_run_id',v.verification_run_id,'execution_id',v.execution_id,'status',v.status,'started_at',v.started_at,'finished_at',v.finished_at) data FROM control.verification_runs v WHERE execution_id=(e.data->>'execution_id')::bigint ORDER BY verification_run_id DESC LIMIT 1)v ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('recovery_state_id',r.recovery_state_id,'status',r.status,'version',r.version,'failure_class',r.failure_class,'error_code',r.error_code,'next_action',r.next_action,'recoverable',r.recoverable,'next_wake_at',r.next_wake_at,'lease_owner',r.lease_owner,'lease_expires_at',r.lease_expires_at,'updated_at',r.updated_at)||jsonb_build_object('condition',jsonb_build_object('exhaustion_audit',jsonb_build_object('all_attempts_audited',r.condition#>'{exhaustion_audit,all_attempts_audited}','action',r.condition#>'{exhaustion_audit,action}','root_cause',left(r.condition#>>'{exhaustion_audit,root_cause}',500),'required_authorization',left(r.condition#>>'{exhaustion_audit,required_authorization}',1000)))) data FROM control.recovery_states r WHERE current_task_id=t.task_id AND status='active' ORDER BY updated_at DESC LIMIT 1)rec ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('operation_id',o.operation_id,'action',o.action,'status',o.status,'infra_retries',o.infra_retries,'next_wake_at',o.next_wake_at,'updated_at',o.updated_at,'created_at',o.created_at)||jsonb_build_object('result',CASE WHEN o.result IS NOT NULL THEN 'true'::jsonb END) data FROM control.runtime_operations o WHERE task_id=t.task_id AND status<>'consumed' ORDER BY created_at DESC LIMIT 1)op ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('pull_request_id',p.pull_request_id,'state',p.state,'updated_at',p.updated_at) data FROM control.pull_requests p WHERE task_id=t.task_id ORDER BY updated_at DESC LIMIT 1)pub ON true
LEFT JOIN LATERAL(SELECT created_at,event_id FROM control.task_events ev WHERE ev.task_id=t.task_id AND event_type IN('task_claimed','execution_started','execution_finished','retry_started','verification_started','verification_finished','publication_started','publication_completed','verifier_only_reaccepted','preexecution_verification_bindings_reconciled','executable_verification_binding_reconciled') ORDER BY created_at DESC LIMIT 1)progress ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('gate_id',g->'gate_id','hard_policy_reason',g->'hard_policy_reason','bs22_path',g->'bs22_path','gate_offers',(SELECT coalesce(jsonb_agg(jsonb_build_object('gate_id',offer->'gate_id','action',offer->'action','type',offer->'type')),'[]') FROM jsonb_array_elements(coalesce(g->'gate_offers','[]')) offer)) data FROM (SELECT control.operator_gate_status((s.run->>'run_id')::uuid) g) q)gates ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('incident_id',g.incident_id,'grant_id',g.grant_id,'granted_at',g.granted_at,'status',j.status,'claim_until',j.claim_until,'next_check_at',j.next_check_at) data FROM control.operator_invocation_extensions g JOIN control.dot_recovery_jobs j USING(incident_id) WHERE g.run_id=(s.run->>'run_id')::uuid AND g.task_id IS NOT DISTINCT FROM t.task_id AND g.kind='incident-investigation-extension' AND g.revoked_at IS NULL AND g.consumed_at IS NULL AND g.granted_at>now()-interval '45 minutes' AND j.status IN('queued','running') ORDER BY g.grant_id LIMIT 1)approved ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('classifications',coalesce(jsonb_agg(jsonb_build_object('execution_id',c->'execution_id','classification_id',c->'classification_id','classification',c->'classification','evidence',jsonb_build_object('root_cause',left(c#>>'{evidence,root_cause}',500),'blocking_checks',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',left(checkrow->>'name',120))),'[]') FROM jsonb_array_elements(coalesce(c#>'{evidence,blocking_checks}','[]')) checkrow)))),'[]')) data FROM jsonb_array_elements(coalesce(control.product_retry_accounting(t.task_id)->'classifications','[]')) c WHERE (c->>'execution_id')::bigint=(e.data->>'execution_id')::bigint)accounting ON true
LEFT JOIN LATERAL(SELECT jsonb_build_object('task_id',d->'task_id','dependencies',(SELECT coalesce(jsonb_agg(dep||jsonb_build_object('owned',EXISTS(SELECT 1 FROM control.workflow_runs owner WHERE owner.status='running' AND (owner.current_task_id=dep->>'task_id' OR EXISTS(SELECT 1 FROM control.dot_task_scope_authorities scope WHERE scope.run_id=owner.run_id AND scope.task_id=dep->>'task_id') OR EXISTS(SELECT 1 FROM control.batch_task_admissions scope WHERE scope.run_id=owner.run_id AND scope.task_id=dep->>'task_id' AND scope.status='admitted'))))),'[]') FROM jsonb_array_elements(coalesce(d->'dependencies','[]'))dep),'decisions',d->'decisions','publication_current',d->'publication_current','packet',jsonb_build_object('publication_boundaries',d#>'{packet,publication_boundaries}','publication_contract',jsonb_build_object('version',d#>'{packet,publication_contract,version}','contract_version',d#>'{packet,publication_contract,contract_version}','task_paths',d#>'{packet,publication_contract,task_paths}','source_paths',d#>'{packet,publication_contract,source_paths}','workstream_paths',d#>'{packet,publication_contract,workstream_paths}','project_paths',d#>'{packet,publication_contract,project_paths}','unresolved_scopes',d#>'{packet,publication_contract,unresolved_scopes}','required_paths',(SELECT coalesce(jsonb_agg(CASE WHEN jsonb_typeof(item)='string' THEN item ELSE item->'path' END),'[]') FROM jsonb_array_elements(coalesce(d#>'{packet,publication_contract,required_paths}','[]'))item)),'publication_authorizations',jsonb_build_object('ordinary',(SELECT coalesce(jsonb_agg(jsonb_build_object('authorized_paths',a->'authorized_paths','requested_paths',a->'requested_paths','revoked_at',a->'revoked_at')),'[]') FROM jsonb_array_elements(coalesce(d#>'{packet,publication_authorizations,ordinary}','[]')) a),'protected',(SELECT coalesce(jsonb_agg(jsonb_build_object('authorized_paths',a->'authorized_paths','requested_paths',a->'requested_paths','revoked_at',a->'revoked_at')),'[]') FROM jsonb_array_elements(coalesce(d#>'{packet,publication_authorizations,protected}','[]')) a)))) data FROM (SELECT control.diagnose_native_run_admission((s.run->>'run_id')::uuid) d WHERE s.run IS NOT NULL AND t.task_id IS NULL)q)admission ON true;
