import {mkdirSync,writeFileSync} from 'node:fs'
import {fileURLToPath} from 'node:url'
export const operatorGateWorkflow={id:'BS22OperatorGates',name:'BS-22 — Operator Gates',active:false,settings:{executionOrder:'v1'},nodes:[
{id:'input',webhookId:'5994b8e5-2cbd-40af-b481-2ba3158b5b11',name:'Select Existing Run',type:'n8n-nodes-base.formTrigger',typeVersion:2.6,position:[0,0],parameters:{authentication:'n8nUserAuth',formTitle:'Building Suit Operator Gates',formDescription:'Resolve an existing task gate. This cannot create runs, increase limits, merge or deploy.',formFields:{values:[{fieldLabel:'Run ID',fieldName:'run_id',fieldType:'text',requiredField:true}]},responseMode:'lastNode',options:{path:'building-suit-operator-gates'}}},
{id:'lookup-input',name:'Validate Run',type:'n8n-nodes-base.code',typeVersion:2,position:[220,0],parameters:{jsCode:"const run=$input.first().json.run_id;if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(run??''))throw Error('Valid existing run ID required');return [{json:{run_id:run,command:'bs-agent operator-gates '+run}}];"}},
{id:'lookup',name:'Read Authoritative Gates',type:'n8n-nodes-base.executeWorkflow',typeVersion:1.3,position:[440,0],parameters:{workflowId:{__rl:true,value:'rzoRWvnSBG7sU1Oh',mode:'list'},workflowInputs:{mappingMode:'defineBelow',value:{command:'={{ $json.command }}'},schema:[{id:'command',displayName:'command',type:'string',canBeUsedToMatch:true}]},options:{waitForSubWorkflow:true}}},
{id:'review-data',name:'Build Gate Review',type:'n8n-nodes-base.code',typeVersion:2,position:[660,0],parameters:{jsCode:"const raw=$input.first().json,p=raw.payload??raw;if(p.ok!==true||!Array.isArray(p.gates))throw Error(p.error??'Gate lookup failed');const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));const gates=p.gates.map(g=>({...g,choice:g.task_id+' — '+g.reason}));const html=gates.length?gates.map(g=>'<section><p>Run: '+esc(g.run_id)+'</p><p>Task: '+esc(g.task_id)+'</p><p>Gate: '+esc(g.action)+' — '+esc(g.reason)+'</p><p>Verification: '+esc(g.verification_run_id)+'</p>'+((g.protected_files??[]).map(f=>'<p>Protected file: '+esc(f.path)+' — '+esc(f.reason)+'</p>').join(''))+'<p>Requested authorization: '+esc(g.requested_authorization)+'</p></section>').join(''):'<p>No supported operator gate exists for this run. Merge, deployment and new scope are not supported.</p>';const details=p.blocked_state?'<p>Current task/gate: '+esc(JSON.stringify(p.blocked_state))+'</p>':'';const fields=[{fieldType:'html',html:html+details}];if(gates.length)fields.push({fieldLabel:'Gate',fieldName:'gate_choice',fieldType:'dropdown',fieldOptions:{values:gates.map(g=>({option:g.choice}))},requiredField:true},{fieldLabel:'Decision',fieldName:'response',fieldType:'dropdown',fieldOptions:{values:[{option:'Approve'},{option:'Reject'}]},requiredField:true});return [{json:{run_id:p.run_id,gates,fields}}];"}},
{id:'review',name:'Approve or Reject',type:'n8n-nodes-base.form',typeVersion:2.5,position:[880,0],parameters:{operation:'page',defineForm:'json',jsonOutput:'={{ JSON.stringify($json.fields) }}',options:{formTitle:'Review Exact Operator Gate'}}},
{id:'validate-response',name:'Validate Operator Response',type:'n8n-nodes-base.code',typeVersion:2,position:[1100,0],parameters:{jsCode:"const reviewed=$('Build Gate Review').first().json,input=$input.first().json;const response=String(input.response??'').toLowerCase();const selected=reviewed.gates.find(g=>g.choice===input.gate_choice);if(!['approve','reject'].includes(response)||!selected)throw Error('No valid reviewed gate selected');return [{json:{command:'bs-agent operator-gate-resolve '+reviewed.run_id+' '+selected.gate_fingerprint+' '+response}}];"}},
{id:'resolve',name:'Resolve Through Control Plane',type:'n8n-nodes-base.executeWorkflow',typeVersion:1.3,position:[1320,0],parameters:{workflowId:{__rl:true,value:'rzoRWvnSBG7sU1Oh',mode:'list'},workflowInputs:{mappingMode:'defineBelow',value:{command:'={{ $json.command }}'},schema:[{id:'command',displayName:'command',type:'string',canBeUsedToMatch:true}]},options:{waitForSubWorkflow:true}}},
{id:'result',name:'Verify Resolution',type:'n8n-nodes-base.code',typeVersion:2,position:[1540,0],parameters:{jsCode:"const p=$input.first().json.payload??$input.first().json;if(p.ok!==true)throw Error(p.error??'Gate changed; reload and review');return [{json:p}];"}},
{id:'done',name:'Operator Receipt',type:'n8n-nodes-base.form',typeVersion:2.5,position:[1760,0],parameters:{operation:'completion',respondWith:'text',completionTitle:'Operator decision recorded',completionMessage:'={{ "Run: " + $json.run_id + " | Task: " + $json.task_id + " | Decision: " + $json.response + " | Receipt: " + $json.resolution_id + ". Dot continues approved work through normal safety gates; rejection grants no authority." }}'}}
],connections:Object.fromEntries(['Select Existing Run','Validate Run','Read Authoritative Gates','Build Gate Review','Approve or Reject','Validate Operator Response','Resolve Through Control Plane','Verify Resolution'].map((name,i,a)=>[name,{main:[[{node:(a[i+1]??'Operator Receipt'),type:'main',index:0}]]}]))}
if(process.argv[1]===fileURLToPath(import.meta.url)){mkdirSync(new URL('./operator-artifacts/',import.meta.url),{recursive:true});writeFileSync(new URL('./operator-artifacts/BS22OperatorGates.json',import.meta.url),JSON.stringify(operatorGateWorkflow,null,2)+'\n')}
