<script setup lang="ts">
import type { ContactInfoItem, SupportRequestCopy, SupportRequestValue } from '@building-suit/contracts'
const model = defineModel<SupportRequestValue>({ required: true })
defineProps<{ eyebrow: string; title: string; intro: string; info: ContactInfoItem[]; formCopy: SupportRequestCopy; categories: Array<{ value: string; label: string }>; identityTitle: string; identityBody: string; pending?: boolean; error?: string | null; sent?: boolean }>()
defineEmits<{ submit: [event: Event] }>()
</script>
<template><main class="bs-contact-page"><section class="bs-contact-page__card"><header class="bs-contact-page__hero"><p>{{ eyebrow }}</p><h1>{{ title }}</h1><div>{{ intro }}</div></header><BsContactInfoGrid :items="info" /><BsSupportRequestForm v-model="model" :copy="formCopy" :categories="categories" :pending="pending" :error="error" :sent="sent" @submit="$emit('submit', $event)" /><footer class="bs-contact-page__identity"><h2>{{ identityTitle }}</h2><p>{{ identityBody }}</p></footer></section></main></template>
<style>
.bs-contact-page { width: 100%; max-width: 64rem; margin-inline: auto; padding: var(--bs-space-8) var(--bs-space-4); }.bs-contact-page__card { overflow: hidden; border: 1px solid var(--bs-border); border-radius: var(--bs-radius-card); background: var(--bs-surface); box-shadow: var(--bs-elevation-1); }.bs-contact-page__hero { padding: var(--bs-space-8) var(--bs-space-6); border-block-end: 1px solid var(--bs-border); background: var(--bs-surface-muted); }.bs-contact-page__hero > p { color: var(--bs-accent); font-size: var(--bs-type-caption-size); font-weight: var(--bs-weight-bold); letter-spacing: .18em; text-transform: uppercase; }.bs-contact-page__hero h1 { margin-top: var(--bs-space-3); font-size: 2rem; font-weight: var(--bs-weight-extrabold); letter-spacing: -.04em; }.bs-contact-page__hero div { max-width: 48rem; margin-top: var(--bs-space-4); color: var(--bs-text-muted); line-height: 1.75rem; }.bs-contact-page__identity { padding: 0 var(--bs-space-6) var(--bs-space-8); }.bs-contact-page__identity h2 { font-size: 1.25rem; font-weight: var(--bs-weight-extrabold); }.bs-contact-page__identity p { margin-top: var(--bs-space-3); color: var(--bs-text-muted); line-height: 1.75rem; }@media (min-width: 640px) { .bs-contact-page__hero { padding-inline: var(--bs-space-9); }.bs-contact-page__identity { padding-inline: var(--bs-space-9); } }@media (min-width: 1024px) { .bs-contact-page { padding-block: var(--bs-space-10); } }
</style>
