import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtempSync,mkdirSync,writeFileSync,readlinkSync,symlinkSync,rmSync,chmodSync} from 'node:fs'
import {spawnSync} from 'node:child_process'
import os from 'node:os'
import path from 'node:path'
import {prepareRuntimeRelease,verifyRuntimeRelease,activateRuntimeRelease} from '../runner/runtime-release.mjs'
function fixture(){const root=mkdtempSync(path.join(os.tmpdir(),'cp-release-')),source=path.join(root,'source'),home=path.join(root,'runtime');mkdirSync(source);mkdirSync(home);mkdirSync(path.join(source,'tooling/control-plane'),{recursive:true});writeFileSync(path.join(source,'tooling/control-plane/test.mjs'),'export const version=1\n');for(const args of [['init','-q'],['add','.'],['-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','-qm','fixture']])assert.equal(spawnSync('git',args,{cwd:source}).status,0);const commit=spawnSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'}).stdout.trim();const candidate=prepareRuntimeRelease({sourceRoot:source,releaseHome:home,commit,files:['tooling/control-plane/test.mjs'],acceptance:{tested:true},schemaVersion:64});return {root,home,source,candidate,cleanup:()=>{chmodSync(candidate.directory,0o755);rmSync(root,{recursive:true,force:true})}}}
test('content addressed release rejects artifact mutation',()=>{const f=fixture();try{assert.equal(verifyRuntimeRelease(f.candidate.directory).commit.length,40);chmodSync(path.join(f.candidate.directory,'tooling/control-plane/test.mjs'),0o644);writeFileSync(path.join(f.candidate.directory,'tooling/control-plane/test.mjs'),'mutated');assert.throws(()=>verifyRuntimeRelease(f.candidate.directory),/component_mismatch/)}finally{f.cleanup()}})
test('one pointer activates all components and CAS refuses competing installer',async()=>{const f=fixture();try{symlinkSync('/previous',path.join(f.home,'current'));const options={releaseHome:f.home,candidate:f.candidate.directory,expectedCurrent:'/previous',requiredChecks:['tested'],restart:async()=>{},readiness:async()=>true};assert.equal((await activateRuntimeRelease(options)).release_id,f.candidate.release_id);assert.equal(readlinkSync(path.join(f.home,'current')),f.candidate.directory);await assert.rejects(activateRuntimeRelease(options),/compare_and_swap/)}finally{f.cleanup()}})
test('failed readiness rolls pointer and services back together',async()=>{const f=fixture();try{symlinkSync('/previous',path.join(f.home,'current'));let restarts=0;await assert.rejects(activateRuntimeRelease({releaseHome:f.home,candidate:f.candidate.directory,expectedCurrent:'/previous',requiredChecks:['tested'],restart:async()=>{restarts++},readiness:async()=>false}),/readiness_failed/);assert.equal(readlinkSync(path.join(f.home,'current')),'/previous');assert.equal(restarts,2)}finally{f.cleanup()}})
test('acceptance gaps prevent switching any component',async()=>{const f=fixture();try{symlinkSync('/previous',path.join(f.home,'current'));await assert.rejects(activateRuntimeRelease({releaseHome:f.home,candidate:f.candidate.directory,expectedCurrent:'/previous',requiredChecks:['n8n_restart_proved']}),/acceptance_incomplete/);assert.equal(readlinkSync(path.join(f.home,'current')),'/previous')}finally{f.cleanup()}})
