import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { operationHasAuthoritativeSuccess } from '../runner/bounded-publication.mjs'
import { publicationHoldOutcome } from '../runner/recovery-evidence.mjs'
import { planSupervisorStep, supervisorStateFingerprint } from '../runner/task-supervisor.mjs'
import { runWakeEligibility } from '../runner/selfhealing.mjs'
import { classifyPublicationFiles, evaluateVerificationAuthority } from '../runner/publication-preflight.mjs'
const authority={authorized:true,mode:'ordinary-draft',run_id:'original-run',task_id:'CP-BOUND-001',contract_fingerprint:'pinned-contract'}
const fixture=()=>({packet:{task:{task_id:'CP-BOUND-001',status:'passed',engine_stage:'publication'}},workflow_run:{status:'running',completed_tasks:0,max_tasks:9},executions:[{execution_id:10,attempt:1,status:'succeeded'}],verification_runs:[{execution_id:10,verification_run_id:11,status:'passed'}],run_publication_authority:authority})
test('bounded 1 ordinary authorized PASS bypasses global hold and resumes publication',()=>{const s=fixture();assert.equal(publicationHoldOutcome({BS_CONTROL_PUBLICATION_HOLD:'1'},authority,'CP-BOUND-001'),null);assert.equal(planSupervisorStep(s).command,'task-publish');assert.equal(evaluateVerificationAuthority({verification:{execution_id:10,status:'passed',state_fingerprint:'same'},executionId:10,stateFingerprint:'same'}).authoritative,true)})
test('bounded 2 grant cannot authorize another task or run-less metadata',()=>{assert.equal(publicationHoldOutcome({BS_CONTROL_PUBLICATION_HOLD:'1'},authority,'CP-OTHER-001').error,'publication_operator_hold');assert.equal(publicationHoldOutcome({BS_CONTROL_PUBLICATION_HOLD:'1'},{...authority,run_id:null},'CP-BOUND-001').error,'publication_operator_hold')})
test('bounded 3 protected file remains gated even in ordinary authorized subtree',()=>{const c=classifyPublicationFiles({files:['apps/ledger-suit/supabase/migrations/new.sql'],workstreamPaths:['apps/ledger-suit/'],ordinaryAuthorizedPaths:['apps/ledger-suit/']});assert.equal(c.blocked.length,1)})
for(const [label,error] of [['merge','merge_authorization_required'],['deployment','deployment_authorization_required']]) test(`bounded ${label} operator gate survives grant`,()=>{const s=fixture();s.recovery={status:'active',next_action:'wait-operator',error_code:error,condition:{fingerprint:supervisorStateFingerprint(s)}};assert.equal(planSupervisorStep(s).next_action,'wait-operator');assert.equal(runWakeEligibility(s.workflow_run,s.recovery,null,Date.now(),s).eligible,false)})
test('bounded 6 scope drift and changed content do not gain authority',()=>{const c=classifyPublicationFiles({files:['apps/shop-suit/app.vue'],workstreamPaths:['packages/ui/'],ordinaryAuthorizedPaths:['apps/ledger-suit/'],projectPaths:['apps/','packages/']});assert.equal(c.waiting.length,1);assert.equal(evaluateVerificationAuthority({verification:{execution_id:10,status:'passed',state_fingerprint:'verified'},executionId:10,stateFingerprint:'drifted'}).authoritative,false)})
test('bounded 7 restart after PASS supersedes only the obsolete publication hold',()=>{const s=fixture();s.recovery={status:'active',next_action:'wait-operator',error_code:'publication_operator_hold',condition:{fingerprint:supervisorStateFingerprint(s)}};assert.equal(planSupervisorStep(s).command,'task-publish');assert.equal(runWakeEligibility(s.workflow_run,s.recovery,null,Date.now(),s).eligible,true);delete s.run_publication_authority;s.recovery.condition.fingerprint=supervisorStateFingerprint(s);assert.equal(planSupervisorStep(s).kind,'wait')})
test('bounded 8 stale verifier timer yields to PASS without new attempt',()=>{const s=fixture();s.runtime_operations=[{action:'task-verify',execution_id:10,status:'running',next_wake_at:new Date(Date.now()+3600000).toISOString()}];const p=planSupervisorStep(s);assert.equal(p.kind,'act');assert.equal(p.command,'task-verify');assert.equal(runWakeEligibility(s.workflow_run,null,s.runtime_operations[0],Date.now(),s).eligible,true);assert.equal(s.executions.length,1)})
test('bounded 9 completed publication defeats stale operation timer and resumes credit',()=>{const s=fixture();s.packet.task.status='complete';s.runtime_operations=[{action:'task-publish',execution_id:10,status:'running',next_wake_at:new Date(Date.now()+3600000).toISOString()}];assert.equal(planSupervisorStep(s).kind,'act');assert.equal(runWakeEligibility(s.workflow_run,null,s.runtime_operations[0],Date.now(),s).eligible,true)})
test('bounded 10 persisted grant changes supervisor fingerprint',()=>{const s=fixture();const before=supervisorStateFingerprint(s);s.run_publication_authority={authorized:false};assert.notEqual(supervisorStateFingerprint(s),before)})
test('bounded 11 published n8n BS10 and BS31 dispatch authoritative supervisor and watchdog',()=>{const rows=readFileSync(process.env.BS_BOUNDED_N8N_FIXTURE ?? new URL('./fixtures/bounded-n8n.jsonl',import.meta.url),'utf8').trim().split('\n').map(JSON.parse);const engine=rows.find(w=>w.name.startsWith('BS-10'));const watch=rows.find(w=>w.name.startsWith('BS-31'));assert.equal(engine.active,true);assert.equal(watch.active,true);assert.ok(JSON.stringify(engine.nodes).includes('task-supervise'));assert.ok(JSON.stringify(watch.nodes).includes('recovery-watch'));assert.ok(watch.nodes.some(n=>n.type==='n8n-nodes-base.scheduleTrigger'))})

test('bounded new repair operation cannot consume success of its previous failed-verification attempt',()=>{const s=fixture();s.packet.task.status='failed';const op={action:'task-retry',execution_id:10,descriptor:{previous_execution_id:10}};assert.equal(operationHasAuthoritativeSuccess(s,op),false);op.execution_id=12;s.executions.push({execution_id:12,status:'succeeded',attempt:2});assert.equal(operationHasAuthoritativeSuccess(s,op),true)})
