import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { stuckRecoveryCandidate,stuckIncidentFingerprint } from '../runner/dot-stuck-recovery.mjs'
import { classifyHealth } from '../runner/dot-health-state.mjs'
import { verificationCommandFailureClass } from '../runner/verification-mode.mjs'
const now=Date.parse('2026-10-06T17:00:00Z')
const health=()=>({state:'STUCK',operator_action_required:false,worker_alive:false,observed_at:new Date(now).toISOString(),run_id:'original',task_id:'SHOP',execution_id:302})
test('STUCK without worker/timer/human gate is recoverable within the next cycle',()=>assert.equal(stuckRecoveryCandidate(health(),now),true))
test('active worker, timers, owner leases and human gates cannot trigger recovery',()=>{for(const change of [{worker_alive:true},{next_wake_at:new Date(now+60000).toISOString()},{controller_lease:{valid:true}},{supervisor_lease:{valid:true}},{operator_action_required:true},{observed_at:new Date(now-90001).toISOString()}])assert.equal(stuckRecoveryCandidate({...health(),...change},now),false)})
test('duplicate watchdog cycles and restart reconstruct one stable incident',()=>{const h=health();assert.equal(stuckIncidentFingerprint(h),stuckIncidentFingerprint({...h,observed_at:new Date(now+60000).toISOString()}));assert.equal(stuckIncidentFingerprint(h),stuckIncidentFingerprint(JSON.parse(JSON.stringify(h))));assert.notEqual(stuckIncidentFingerprint(h),stuckIncidentFingerprint({...h,execution_id:303}))})
test('fixture bind collisions are infrastructure, ordinary assertions remain product',()=>{assert.equal(verificationCommandFailureClass({passed:false,output:'Error: listen EADDRINUSE: address already in use 127.0.0.1:64321'}),'verification-infrastructure');assert.equal(verificationCommandFailureClass({passed:false,output:'Expected true, received false'}),'verification-product-defect')})
test('legitimate product exhaustion becomes NEEDS_ME, reclaimed non-product does not',()=>{const f={run:{status:'failed',run_id:'same',completed_tasks:1,max_tasks:14},task:{status:'failed',task_id:'SHOP'},execution:{status:'failed',execution_id:302,attempt:3},policy:{max_attempts:3},accounting:{consumed:3,all_product:true}};assert.equal(classifyHealth(f,{},now).operator_action_required,true);assert.equal(classifyHealth({...f,accounting:{consumed:1,all_product:false}}, {},now).operator_action_required,false)})
test('installed watchdog includes failed non-Shared runs and claims before supported dispatch',()=>{const source=readFileSync(new URL('../runner/bs-agent.mjs',import.meta.url),'utf8');const code=source.slice(source.indexOf('function recoveryWatch()'),source.indexOf('function recoverWorkflowRun()'));assert.match(code,/status='failed' AND current_task_id IS NOT NULL/);assert.ok(code.indexOf('claim_dot_stuck_recovery')<code.indexOf("'run-recover'"));assert.match(code,/receiptLocked/);assert.match(code,/worker_active/);assert.match(code,/stuckRecoveryCandidate/);assert.match(code,/health_collection/)})
