import test from 'node:test'
import assert from 'node:assert/strict'
import {dispatchRecovery,recoveryFamily,recoveryIdentity,validateIncidentRepair} from '../runner/dot-general-recovery.mjs'
import {classifyHealth} from '../runner/dot-health-state.mjs'
import {supervisorStateFingerprint,planSupervisorStep} from '../runner/task-supervisor.mjs'
const now=Date.now(), h=()=>({run_id:'same-run',task_id:'same-task',execution_id:302,state:'STUCK',operator_action_required:false,worker_alive:false,observed_at:new Date(now).toISOString()})
function store(){const jobs=new Map();let launches=0;return {jobs,get launches(){return launches},claim:async(run,id,family)=>{if(jobs.has(id))return {claimed:false,job:jobs.get(id)};const job={incident_id:id,run_id:run,root_family:family,owner:family.startsWith('unknown')?'Codex':'Dot'};jobs.set(id,job);return {claimed:true,job}},start:async()=>{launches++}}}
function snapshot(origin='normal'){return {packet:{task:{task_id:'same-task',status:'passed'}},executions:[{execution_id:302,attempt:3,status:origin==='reaccepted'?'failed':'succeeded'}],verification_runs:[{verification_run_id:304,execution_id:302,status:'passed',metadata:{origin,verifier_only_reacceptance:origin==='reaccepted'}}],failures:[],publications:[],runtime_operations:[]}}
for(const origin of ['normal','reaccepted','reopened','infra-recovered','replay'])test(`${origin} authoritative PASS enters the same publication machine`,async()=>{const s=snapshot(origin);assert.equal(planSupervisorStep(s).command,'task-publish');const st=store();await dispatchRecovery({health:h(),snapshot:s,...st,now});assert.equal([...st.jobs.values()][0].root_family,'publication-handoff');assert.equal(st.launches,1)})
test('STUCK/NO with stale or unexpired advisory lease owns supported recovery this cycle',async()=>{const st=store();const health={...h(),controller_lease:{valid:true},supervisor_lease:{valid:true}};await dispatchRecovery({health,snapshot:snapshot(),...st,now});assert.equal(st.launches,1)})
test('duplicate watchdog cycles and process restart keep one durable incident',async()=>{const st=store();await dispatchRecovery({health:h(),snapshot:snapshot(),...st,now});await dispatchRecovery({health:JSON.parse(JSON.stringify(h())),snapshot:snapshot(),...st,now});assert.equal(st.launches,1);assert.equal(st.jobs.size,1)})
test('unknown incident automatically launches Codex without a product execution',async()=>{const st=store();await dispatchRecovery({health:h(),snapshot:{},...st,now});assert.equal([...st.jobs.values()][0].owner,'Codex');assert.equal(st.launches,1)})
test('semantic catalog can reuse a learned regression protected strategy',async()=>{let owner;const claim=async(run,id,family)=>({claimed:true,job:{owner:new Map([['unknown-lifecycle','Dot']]).get(family),incident_id:id}});await dispatchRecovery({health:h(),snapshot:{},claim,start:async j=>{owner=j.owner},now});assert.equal(owner,'Dot')})
test('true human gates and live workers do not launch recovery',async()=>{for(const change of [{operator_action_required:true},{worker_alive:true},{state:'WAITING_OPERATOR'},{state:'WAITING_TIMER'}]){const st=store();await dispatchRecovery({health:{...h(),...change},snapshot:snapshot(),...st,now});assert.equal(st.launches,0)}})
test('infra accounting routes same execution rather than a new product attempt',()=>{for(const cls of ['CONFIGURATION','VERIFIER_INFRA','REPOSITORY_WORKTREE','TRANSIENT_INFRASTRUCTURE']){const s={retry_accounting:{classifications:[{classification:cls}]}};assert.notEqual(recoveryFamily(h(),s),'product-repair')}assert.equal(recoveryIdentity(h()),recoveryIdentity({...h(),observed_at:new Date(now+2000).toISOString()}))})
test('incident patches cannot touch product paths, providers, SQL, merge or deployment scripts',()=>{for(const file of ['apps/shop-suit/app/app.vue','tooling/deploy.mjs','tooling/control-plane/sql/999.sql','.env'])assert.throws(()=>validateIncidentRepair({files:[file,'tooling/control-plane/tests/new.test.mjs'],regression:'tooling/control-plane/tests/new.test.mjs',rootFamily:'unknown-lifecycle',base:'base',head:'base'}));assert.equal(validateIncidentRepair({files:['tooling/control-plane/runner/fix.mjs','tooling/control-plane/tests/new.test.mjs'],regression:'tooling/control-plane/tests/new.test.mjs',rootFamily:'unknown-lifecycle',base:'base',head:'base'}),true)})
test('publication completion transitions to credit, unowned next task to acquisition',()=>{assert.equal(recoveryFamily(h(),{packet:{task:{status:'complete'}}}),'completion-credit');assert.equal(recoveryFamily({...h(),task_id:null},{}),'controller-acquisition')})

test('exact native reacceptance proof supersedes the old publisher eligibility stop',()=>{const s=snapshot('reaccepted');s.run_publication_authority={authorized:true,mode:'ordinary-draft',task_id:'same-task',run_id:'same-run',contract_fingerprint:'current'};s.publication_execution_eligible=true;s.recovery={status:'resolved',next_action:'safety-stop',failure_class:'safety-stop',error_code:'Latest execution lacks successful implementation or exact guarded reacceptance.',metadata:{child_command:'task-publish'}};s.recovery.condition={fingerprint:supervisorStateFingerprint(s)};assert.equal(planSupervisorStep(s).command,'task-publish');s.publication_execution_eligible=false;s.recovery.condition.fingerprint=supervisorStateFingerprint(s);assert.equal(planSupervisorStep(s).kind,'terminal');s.publication_execution_eligible=true;s.recovery.error_code='publication_protected_path_operator_wait';s.recovery.condition.fingerprint=supervisorStateFingerprint(s);assert.equal(planSupervisorStep(s).kind,'terminal')})

// A pending prerequisite outside every authorized run cannot be started by recovery.
test('unowned prerequisite and completed frozen scope are real operator gates, not silent automatic waits',()=>{const base={key:'run:x',run:{run_id:'x',status:'running',max_tasks:14,completed_tasks:2}};for(const patch of [{unowned_prerequisite:'SHARED-PREREQUISITE'},{bounded_scope_exhausted:true}]){const health=classifyHealth({...base,...patch},{},now);assert.equal(health.state,'WAITING_OPERATOR');assert.equal(health.operator_action_required,true)}})

test('learned runtime repair cannot replace its verifier, installer, operator or secret boundary',()=>{
 for(const name of ['task-verifier.mjs','trusted-verifier-receipt.mjs','runtime-release.mjs','incident-release-installer.mjs','operator-gate.mjs','control-adoption.mjs','codex-child-environment.mjs'])assert.throws(()=>validateIncidentRepair({files:['tooling/control-plane/runner/'+name,'tooling/control-plane/tests/new.test.mjs'],regression:'tooling/control-plane/tests/new.test.mjs',rootFamily:'unknown-lifecycle',base:'base',head:'base'}),/incident_protected_runtime_guard/)
})
