import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dotClassification, incidentIdentity, effectiveFailureClass, parentContinuation, cleanupEligibility, repairEvidenceHeader } from '../runner/dot.mjs'
import { planSupervisorStep, classifySupervisorFailure, supervisorStateFingerprint } from '../runner/task-supervisor.mjs'
import { verificationCommandFailureClass } from '../runner/verification-mode.mjs'
import { runWakeEligibility } from '../runner/selfhealing.mjs'
const run={run_id:'11111111-2222-4333-8444-555555555555',status:'running',completed_tasks:0,max_tasks:3,current_task_id:'DOT-FIXTURE-001'}
const make=()=>({workflow_run:{...run},packet:{task:{task_id:'DOT-FIXTURE-001',status:'failed',allowed_paths:['tooling/'],acceptance_criteria:['must pass'],verification_plan:['pnpm test']},retry_policy:{max_attempts:3},requirements:[]},executions:[{execution_id:1,attempt:1,status:'failed',worktree_path:'/fixture'}],failures:[{execution_id:1,failure_id:1,failure_class:'verification-product-defect',metadata:{classification:{failure_class:'verification-product-defect'}}}]})
for(const reason of ['generator_disposable_fixture_runner_not_registered','missing_generated_fixture_boundary_runner','browser_configuration_discovery_failed'])test(`Dot ${reason} cannot consume product retry`,()=>{
 const s=make();s.executions[0].attempt=3;s.failures[0].metadata.verification_probe={checks:[{name:'required',required:true,status:'not_run',failure_class:'verification-product-defect',selection_reason:reason}]}
 assert.equal(effectiveFailureClass(s,'verification-product-defect'),'verification-configuration');assert.equal(planSupervisorStep(s).command,undefined);assert.notEqual(planSupervisorStep(s).reason,'retry_budget_exhausted')
})
test('Dot actual assertion alongside missing binding remains product',()=>{const s=make();s.failures[0].metadata.checks=[{status:'not_run',selection_reason:'generator_disposable_fixture_runner_not_registered'},{status:'fail',failure_class:'verification-product-defect'}];assert.equal(effectiveFailureClass(s,'verification-product-defect'),'verification-product-defect');assert.equal(planSupervisorStep(s).command,'task-retry')})
test('Dot unknown failed implementation cannot spend a product attempt',()=>{const s=make();s.failures=[];assert.equal(planSupervisorStep(s).reason,'unknown_failure_outcome');assert.equal(planSupervisorStep(s).command,undefined)})
test('Dot uppercase classification beats error text',()=>{assert.equal(classifySupervisorFailure({payload:{error:'network permission branch',classification:{failure_class:'PRODUCT_DEFECT'}},attempt:1,maxAttempts:3}).command,'task-retry');assert.equal(classifySupervisorFailure({payload:{error:'assertion',classification:{failure_class:'TRANSIENT_INFRASTRUCTURE'}},attempt:3,maxAttempts:3}).next_action,'wait-external')})
test('Dot incident replay and execution identity',()=>{const s=make(),p=planSupervisorStep(s);assert.deepEqual(incidentIdentity(s,p),incidentIdentity(JSON.parse(JSON.stringify(s)),p));const x=make();x.executions[0].execution_id=2;assert.notDeepEqual(incidentIdentity(x,p),incidentIdentity(s,p))})
test('Dot human classes and exhausted budgets are distinct',()=>{for(const [a,b] of [['operator-wait','OPERATOR_AUTHORIZATION'],['decision-wait','DECISION_REQUIRED'],['verification-required-check-unavailable','EXTERNAL_EVIDENCE'],['safety-stop','TERMINAL_SAFETY'],['not-registered','UNKNOWN']])assert.equal(dotClassification(a),b);assert.equal(dotClassification('safety-stop','retry_budget_exhausted'),'RETRY_BUDGET_EXHAUSTED')})
test('Dot active process and future timer preserve same attempt',()=>{const s=make();s.executions[0].status='running';s.packet.task.status='in_progress';assert.equal(planSupervisorStep(s).reason,'execution_in_flight');assert.equal(runWakeEligibility(run,null,{next_wake_at:'2099-01-01'}).eligible,false);assert.equal(s.executions.length,1)})
test('Dot stale operator recovery yields to changed actionable state',()=>{const s=make();s.packet.task.status='passed';s.watchdog_plan=planSupervisorStep(s);const recovery={status:'active',next_action:'wait-operator',condition:{fingerprint:'old'}};assert.equal(runWakeEligibility(run,recovery,null,Date.now(),s).eligible,true);assert.equal(runWakeEligibility(run,recovery,null).eligible,false)})
test('Dot unchanged true gate stays held',()=>{const s=make();s.packet.task.status='blocked';s.recovery={status:'active',next_action:'wait-operator',condition:{fingerprint:supervisorStateFingerprint(s)}};s.watchdog_plan=planSupervisorStep(s);assert.equal(runWakeEligibility(run,s.recovery,null,Date.now(),s).eligible,false)})
for(const dirty of [false,true])test(`Dot stack parent advancement preserves dirty=${dirty}`,()=>assert.deepEqual(parentContinuation({sameBranch:true,oldPresent:true,newPresent:true,ancestor:true,containsOld:true,dirty,workerActive:dirty}),{safe:true,action:'continue-preserved-base',dirty_preserved:dirty,worker_preserved:dirty}))
test('Dot divergent parents stay protected',()=>{for(const x of [{sameBranch:false},{ancestor:false},{containsOld:false},{newPresent:false}])assert.equal(parentContinuation({sameBranch:true,ancestor:true,containsOld:true,oldPresent:true,newPresent:true,dirty:true,...x}).safe,false)})
const clean={activeReference:false,workerActive:false,clean:true,published:true,integrated:true,openChild:false,uniqueWork:false}
for(const [key,value] of [['activeReference',true],['workerActive',true],['clean',false],['published',false],['integrated',false],['openChild',true],['uniqueWork',true]])test(`Dot cleanup refuses ${key}=${value}`,()=>assert.equal(cleanupEligibility({...clean,[key]:value}),false))
test('Dot clean integrated unused work may be retired',()=>assert.equal(cleanupEligibility(clean),true))
for(const output of ['No tests found','Playwright Test did not expect test',"Executable doesn't exist",'Failed to load playwright config'])test(`Dot harness ${output} is configuration`,()=>assert.equal(verificationCommandFailureClass({name:'browser',passed:false,output}),'verification-configuration'))
test('Dot browser assertions remain product',()=>assert.equal(verificationCommandFailureClass({name:'browser',passed:false,output:'Expected 200, received 403'}),'verification-product-defect'))
test('Dot event and cadence use same owner',()=>{const w=JSON.parse(readFileSync(new URL('../n8n/artifacts/BS31SelfHealingRecovery.json',import.meta.url)));assert.equal(w.nodes.find(n=>n.name==='Recovery Cadence').parameters.rule.interval[0].minutesInterval,2);assert.equal(w.connections['Control State Changed'].main[0][0].node,w.connections['Recovery Cadence'].main[0][0].node);assert.equal(w.nodes.filter(n=>n.type==='n8n-nodes-base.executeWorkflow').length,1)})
test('Dot prompt includes failures, passing checks and boundaries',()=>{const s=make();s.verification_results=[{status:'pass',check_name:'good'},{status:'fail',check_name:'bad'}];const p=JSON.parse(repairEvidenceHeader(s,2));for(const field of ['run_id','task_id','execution_id','attempt','classification','worktree','allowed_paths','requirements','acceptance','failed_checks','successful_checks','required_regression','preservation','prohibited_actions'])assert.ok(Object.hasOwn(p,field),field);assert.equal(p.successful_checks[0].check_name,'good');assert.equal(p.run_id,run.run_id)})

test('Dot bounded verifier failure reaccepts the same failed execution without a product attempt',()=>{const s=make();s.failures[0].metadata.checks=[{status:'not_run',selection_reason:'generator_disposable_fixture_runner_not_registered'}];s.run_publication_authority={authorized:true};s.executions[0].attempt=3;const p=planSupervisorStep(s);assert.equal(p.command,'task-reaccept');assert.equal(p.execution.execution_id,1);assert.equal(p.execution.attempt,3)})
test('Dot authoritative reacceptance supersedes stale exhausted timer and recovery',()=>{const s=make();s.packet.task.status='passed';s.verification_runs=[{execution_id:1,status:'passed',metadata:{verifier_only_reacceptance:true}}];assert.equal(runWakeEligibility(run,{next_action:'safety-stop',error_code:'retry_budget_exhausted'},null,Date.now(),s).eligible,true)})
test('Dot unrelated safety gate survives verifier reacceptance',()=>{const s=make();s.packet.task.status='passed';s.verification_runs=[{execution_id:1,status:'passed',metadata:{verifier_only_reacceptance:true}}];assert.equal(runWakeEligibility(run,{next_action:'safety-stop',error_code:'ambiguous_source'},null,Date.now(),s).eligible,false)})
