import test from 'node:test';import assert from 'node:assert/strict';import {queueDraftSourcePaths,draftSourceArtifact} from '../runner/draft-source-policy.mjs';import {classifyPublicationFiles} from '../runner/publication-preflight.mjs';import {unattendedSensitiveFiles} from '../runner/unattended-publication.mjs';import {supersededQueueSourceHold} from '../runner/bounded-publication.mjs';
const files=['apps/p/supabase/migrations/a.sql','apps/p/supabase/config.toml','apps/p/server/api/owner.post.ts','tooling/database/test-shop-plan-limits-local.mjs'].map(file=>({file,object:'b'.repeat(40)}));
function fixture(){return {authority:{authorized:true,unattended_queue_authority:true,task_id:'T',run_id:'R',queue_authority_event:19,draft_source_policy:{version:1,mode:'verified-source-draft-only',task_id:'T',run_id:'R',queue_event:19,execution_id:324,verification_run_id:359,parent_sha:'a'.repeat(40),state_fingerprint:'state',files,ancillary:[files[3]],merge:false,deploy:false,hosted_sql:false}},task:{task_id:'T'},execution:{execution_id:324,parent_sha:'a'.repeat(40),branch_name:'codex/p/task'},verification:{status:'passed',execution_id:324,verification_run_id:359,state_fingerprint:'state',verified_state:{files}},taskPaths:['apps/p/**'],projectPaths:['apps/p/','tooling/']}}
test('exact queue policy permits verified source artifacts and one exact ancillary file',()=>{const x=fixture(),paths=queueDraftSourcePaths(x);assert.deepEqual(paths,files.map(f=>f.file));assert.equal(classifyPublicationFiles({files:paths,queueSourcePaths:paths,projectPaths:x.projectPaths}).blocked.length,0);assert.deepEqual(unattendedSensitiveFiles(paths,{verifiedOwnerPaths:paths}),[])});
for(const [name,mutate] of Object.entries({revoked:x=>x.authority.authorized=false,staleQueue:x=>x.authority.queue_authority_event=20,wrongRun:x=>x.authority.run_id='other',wrongTask:x=>x.task.task_id='other',wrongExecution:x=>x.execution.execution_id=325,wrongVerification:x=>x.verification.verification_run_id=360,failed:x=>x.verification.status='failed',changedState:x=>x.verification.state_fingerprint='new',changedParent:x=>x.execution.parent_sha='c'.repeat(40),main:x=>x.execution.branch_name='main',deployment:x=>x.authority.draft_source_policy.deploy=true,hostedSQL:x=>x.authority.draft_source_policy.hosted_sql=true,merge:x=>x.authority.draft_source_policy.merge=true})) test(`denies ${name}`,()=>{const x=fixture();mutate(x);assert.deepEqual(queueDraftSourcePaths(x),[])});
test('scope, tampered ancillary, arbitrary tooling and credentials remain denied',()=>{const x=fixture();x.taskPaths=['apps/other/**'];assert.deepEqual(queueDraftSourcePaths(x),[files[3].file]);x.verification.verified_state.files=[{...files[3],object:'d'.repeat(40)}];assert.deepEqual(queueDraftSourcePaths(x),[]);for(const p of ['tooling/anything.mjs','apps/p/server/api/secrets.ts','apps/p/.env','apps/p/vercel.json','.github/workflows/deploy.yml'])assert.equal(draftSourceArtifact(p),false)});
test('legacy protected hold is superseded by current policy, not synthetic receipt',()=>{const x=fixture();const snap={packet:{task:x.task,publication_boundaries:{task_paths:x.taskPaths,project_paths:x.projectPaths}},run_publication_authority:x.authority,executions:[x.execution],verification_runs:[{...x.verification,metadata:{verified_state:{...x.verification.verified_state,fingerprint:'state'}}}],recovery:{error_code:'publication_protected_path_operator_wait',failure_id:1},failures:[{failure_id:1,execution_id:324,metadata:{protected_paths:[files[0].file]}}]};assert.equal(supersededQueueSourceHold(snap),true);snap.run_publication_authority.authorized=false;assert.equal(supersededQueueSourceHold(snap),false)});

test('source-only shared auth and contracts remain queue scoped; provider, secret and control actions do not',()=>{for(const file of ['packages/auth/src/session.ts','packages/contracts/src/permissions.ts','apps/p/app/utils/auth.ts'])assert.equal(draftSourceArtifact(file),true);for(const file of ['apps/p/deploy/job.mjs','apps/p/n8n/live.json','packages/auth/credentials.json','tooling/control-plane/runner/bs-agent.mjs'])assert.equal(draftSourceArtifact(file),false)})
