import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {spawnSync} from 'node:child_process'
import {auditAttempts} from '../runner/retry-exhaustion-audit.mjs'
import {classifyHealth} from '../runner/dot-health-state.mjs'
import {requiresWatchdogAction,currentStateSql} from '../runner/dot-current-state.mjs'
import {planSupervisorStep} from '../runner/task-supervisor.mjs'
const now=Date.now(),past=new Date(now-120000).toISOString()
const approved={incident_id:'existing',grant_id:2,status:'queued',next_check_at:past}
const input={run:{run_id:'run',status:'running',current_task_id:'task',completed_tasks:2,max_tasks:14},task:{task_id:'task',status:'failed'},execution:{execution_id:312,status:'succeeded',attempt:1},verification:{verification_run_id:334,status:'failed'},incident_recovery:{...approved,owner:'Codex',action:'incident-investigate'},approved_incident:approved}
const snapshot={packet:{task:{task_id:'task',status:'failed'},retry_policy:{max_attempts:5}},executions:[{execution_id:313,attempt:1,status:'succeeded'}],verification_runs:[{execution_id:313,verification_run_id:335,status:'failed'}],verification_results:[{execution_id:313,verification_run_id:335,check_name:'passed',status:'pass',metadata:{required:true,failure_evidence:{version:2,classification:'UNKNOWN'}}},{execution_id:313,verification_run_id:335,check_name:'verifier-resume-infrastructure',status:'fail',metadata:{required:true,failure_class:'verification-infrastructure'}}],failures:[{execution_id:313,failure_class:'verification-infrastructure',error_code:'interrupted_verification_has_immutable_receipts',metadata:{classification:{failure_class:'verification-infrastructure',recovery_action:'wait-external'},checks:[{name:'verifier-resume-infrastructure',status:'fail',required:true,failure_class:'verification-infrastructure'}]}}]}
test('approved same-incident work remains automatically actionable through 100 event permutations',()=>{
 for(let n=0;n<100;n++){const i=structuredClone(input);i.latest_event_id=n%2?41:42;const h=classifyHealth(i,{},now);assert.equal(h.state,'RECONCILING');assert.equal(h.operator_action_required,false);assert.equal(requiresWatchdogAction(i,h,now),true);assert.equal(h.incident_id,'existing')}
})
test('passing evidence cannot erase the failed infrastructure check or consume a product slot',()=>{const a=auditAttempts(snapshot);assert.equal(a.entries[0].classification,'VERIFIER_INFRA');assert.equal(a.entries[0].blocking_checks[0].name,'verifier-resume-infrastructure');assert.equal(a.action,'same-attempt-recovery');assert.equal(a.consumed,0)})
test('failed verification routes the existing execution to runtime reconciliation',()=>{const s=structuredClone(snapshot);s.exhaustion_audit=auditAttempts(s);s.runtime_operations=[{operation_id:'existing',status:'pending',action:'task-verify',execution_id:313,next_wake_at:past}];const p=planSupervisorStep(s);assert.equal(p.command,'task-verify');assert.equal(p.reason,'runtime_operation_resume');assert.equal(p.execution.execution_id,313)})
test('passing verification routes to publication on the same execution',()=>{const s=structuredClone(snapshot);s.packet.task.status='passed';s.verification_runs[0].status='passed';s.failures=[];s.verification_results=[{verification_run_id:335,status:'pass',metadata:{required:true},trusted_receipt:{version:2},trusted_registration:{version:2}}];const p=planSupervisorStep(s);assert.equal(p.command,'task-publish');assert.equal(p.execution.execution_id,313)})
test('stale non-actionable incident reports do not fabricate a human authority gate',()=>{const i=structuredClone(input);delete i.approved_incident;i.incident_recovery.status='human-gate';i.gate_status={gate_offers:[],hard_policy_reason:'runtime_infrastructure'};const h=classifyHealth(i,{},now);assert.equal(h.operator_action_required,false);assert.notEqual(h.state,'WAITING_OPERATOR');assert.equal(requiresWatchdogAction(i,h,now),true)})
test('dependency completion makes an existing idle bounded run actionable without scope expansion',()=>{const i={run:{run_id:'shared',status:'running',completed_tasks:0,max_tasks:4},task:null,next_eligible_task:'BS-REALTIME-FOUNDATION-001'};const h=classifyHealth(i,{},now);assert.equal(h.state,'STUCK');assert.equal(h.operator_action_required,false);assert.equal(requiresWatchdogAction(i,h,now),true)})
test('compact scan prioritizes unconsumed exact approvals without evidence/history download',()=>{const sql=currentStateSql();assert.match(sql,/'approved_incident',approved.data/);assert.match(sql,/g\.consumed_at IS NULL/);assert.match(sql,/ORDER BY EXISTS\(SELECT 1 FROM control.operator_invocation_extensions/);assert.doesNotMatch(sql,/jsonb_agg\(to_jsonb\(.*(?:failures|task_events)/)})
test('actual PostgreSQL lifecycle outbox, duplicate claim, restart and dropped webhook invariants',{skip:!process.env.CP_EGRESS_TEST_DATABASE},()=>{assert.match(process.env.CP_EGRESS_TEST_DATABASE,/^cp_egress_/);const sql=readFileSync(new URL('./lifecycle-wake-smoke.sql',import.meta.url),'utf8');const r=spawnSync('docker',['exec','-i',process.env.CP_EGRESS_TEST_CONTAINER??'cp-remediation-disposable-20261007','psql','-U','postgres','-d',process.env.CP_EGRESS_TEST_DATABASE,'-XqAt','-v','ON_ERROR_STOP=1'],{input:sql,encoding:'utf8',maxBuffer:2*1024*1024});assert.equal(r.status,0,r.stderr)})
