import test from 'node:test'
import assert from 'node:assert/strict'
import vm from 'node:vm'
import {readFileSync} from 'node:fs'
import {dispatchRecovery} from '../runner/dot-general-recovery.mjs'
import {operatorGateWorkflow as w} from '../n8n/operator-gates.mjs'
const code=n=>w.nodes.find(x=>x.name===n).parameters.jsCode
function run(name,json,refs={}){return vm.runInNewContext("(()=>{"+code(name)+"})()",{$input:{first:()=>({json})},$:(n)=>({first:()=>({json:refs[n]})})})}
test('operator workflow requires n8n user authentication and never changes Continue run limits',()=>{assert.equal(w.nodes[0].parameters.authentication,'n8nUserAuth');assert.equal(w.nodes[0].parameters.options.path,'building-suit-operator-gates');assert.equal(w.nodes[0].parameters.formFields.values.length,1);assert.match(code('Validate Run'),/operator-gates/);assert.doesNotMatch(JSON.stringify(w.nodes),/task-retry|run-start|merge approve|deploy approve/);})
test('run input cannot inject shell commands',()=>{assert.throws(()=>run('Validate Run',{run_id:'run; dangerous'}));assert.equal(run('Validate Run',{run_id:'2518c051-fb28-4641-ae03-c046d7c30807'})[0].json.command,'bs-agent operator-gates 2518c051-fb28-4641-ae03-c046d7c30807')})
test('review shows exact run task reason and requested authorization with escaped content',()=>{const out=run('Build Gate Review',{ok:true,run_id:'run',gates:[{run_id:'run',task_id:'task',action:'ordinary-publication',reason:'<script>',requested_authorization:'exact approval',gate_fingerprint:'a'.repeat(32)}]})[0].json;assert.match(out.fields[0].html,/run/);assert.match(out.fields[0].html,/task/);assert.match(out.fields[0].html,/&lt;script&gt;/);assert.match(out.fields[0].html,/exact approval/);assert.deepEqual(JSON.parse(JSON.stringify(out.fields[2].fieldOptions.values)),[{option:'Approve'},{option:'Reject'}]);})
test('response is bound to server reviewed offer, not user supplied run or task',()=>{const reviewed={run_id:'run',gates:[{gate_fingerprint:'a'.repeat(32),choice:'task — publication_operator_hold'}]};assert.throws(()=>run('Validate Operator Response',{gate_choice:'forged',response:'Approve'},{'Build Gate Review':reviewed}));assert.match(run('Validate Operator Response',{gate_choice:'task — publication_operator_hold',response:'Reject',run_id:'other'},{'Build Gate Review':reviewed})[0].json.command,/run a+ reject$/)})
test('failed authoritative resolution never appears successful',()=>{assert.throws(()=>run('Verify Resolution',{payload:{ok:false,error:'stale'}}));assert.equal(run('Verify Resolution',{payload:{ok:true,resolution_id:1}})[0].json.resolution_id,1)})

test('one temporarily unavailable snapshot cannot abort other run gate recovery',()=>{const source=readFileSync(new URL('../runner/bs-agent.mjs',import.meta.url),'utf8');const body=source.slice(source.indexOf('if(candidate.current_task_id){const auditSnapshot='),source.indexOf('      const nativeGate=',source.indexOf('if(candidate.current_task_id){const auditSnapshot=')));const outcomes=[],audits=[];vm.runInNewContext('for(const candidate of candidates){'+body+'}',{candidates:[{run_id:'first',current_task_id:'missing'},{run_id:'second',current_task_id:'valid'}],outcomes,supervisorSnapshot:id=>id==='missing'?null:{exhaustion_audit:{consumed:0}},controlQuery:(sql,v)=>audits.push(v.task)});assert.deepEqual(audits,['valid']);assert.equal(outcomes[0].owner,'Dot');assert.equal(outcomes[0].retry_after_ms,30000)})

test('idle run with no task snapshot routes admission recovery without crashing other operator gates',async()=>{let family;const health={run_id:'same-run',task_id:null,state:'WAITING_ADMISSION',operator_action_required:false,worker_alive:false,observed_at:new Date().toISOString()};const result=await dispatchRecovery({health,snapshot:null,claim:async(run,key,f)=>{family=f;return {claimed:false}},start:async()=>{throw Error('unexpected duplicate')}});assert.equal(family,'controller-acquisition');assert.equal(result.claimed,false)})

test('protected review displays verification exact file and protection reason without execution authority',()=>{const out=run('Build Gate Review',{ok:true,run_id:'run',gates:[{task_id:'task',run_id:'run',action:'protected-publication',reason:'protected',verification_run_id:313,protected_files:[{path:'migration.sql',reason:'Database schema file; publication does not execute SQL'}],requested_authorization:'No merge or deployment',gate_fingerprint:'a'.repeat(32)}]})[0].json;assert.match(out.fields[0].html,/Verification: 313/);assert.match(out.fields[0].html,/migration.sql/);assert.match(out.fields[0].html,/does not execute SQL/)})
