import test from 'node:test'
import assert from 'node:assert/strict'
import vm from 'node:vm'
import {operatorGateWorkflow as w} from '../n8n/operator-gates.mjs'
const code=n=>w.nodes.find(x=>x.name===n).parameters.jsCode
function run(name,json,refs={}){return vm.runInNewContext("(()=>{"+code(name)+"})()",{$input:{first:()=>({json})},$:(n)=>({first:()=>({json:refs[n]})})})}
test('operator workflow requires n8n user authentication and never changes Continue run limits',()=>{assert.equal(w.nodes[0].parameters.authentication,'n8nUserAuth');assert.equal(w.nodes[0].parameters.options.path,'building-suit-operator-gates');assert.equal(w.nodes[0].parameters.formFields.values.length,1);assert.match(code('Validate Run'),/operator-gates/);assert.doesNotMatch(JSON.stringify(w.nodes),/task-retry|run-start|merge approve|deploy approve/);})
test('run input cannot inject shell commands',()=>{assert.throws(()=>run('Validate Run',{run_id:'run; dangerous'}));assert.equal(run('Validate Run',{run_id:'2518c051-fb28-4641-ae03-c046d7c30807'})[0].json.command,'bs-agent operator-gates 2518c051-fb28-4641-ae03-c046d7c30807')})
test('review shows exact run task reason and requested authorization with escaped content',()=>{const out=run('Build Gate Review',{ok:true,run_id:'run',gates:[{run_id:'run',task_id:'task',action:'ordinary-publication',reason:'<script>',requested_authorization:'exact approval',gate_fingerprint:'a'.repeat(32)}]})[0].json;assert.match(out.fields[0].html,/run/);assert.match(out.fields[0].html,/task/);assert.match(out.fields[0].html,/&lt;script&gt;/);assert.match(out.fields[0].html,/exact approval/);assert.deepEqual(JSON.parse(JSON.stringify(out.fields[2].fieldOptions.values)),[{option:'Approve'},{option:'Reject'}]);})
test('response is bound to server reviewed offer, not user supplied run or task',()=>{const reviewed={run_id:'run',gates:[{gate_fingerprint:'a'.repeat(32)}]};assert.throws(()=>run('Validate Operator Response',{gate_fingerprint:'b'.repeat(32),response:'Approve'},{'Build Gate Review':reviewed}));assert.match(run('Validate Operator Response',{gate_fingerprint:'a'.repeat(32),response:'Reject',run_id:'other'},{'Build Gate Review':reviewed})[0].json.command,/run a+ reject$/)})
test('failed authoritative resolution never appears successful',()=>{assert.throws(()=>run('Verify Resolution',{payload:{ok:false,error:'stale'}}));assert.equal(run('Verify Resolution',{payload:{ok:true,resolution_id:1}})[0].json.resolution_id,1)})
