import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,existsSync,readFileSync} from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {auditAttempts,emptyComponentFixture} from '../runner/retry-exhaustion-audit.mjs'
import {classifyHealth} from '../runner/dot-health-state.mjs'
import {dispatchRecovery} from '../runner/dot-general-recovery.mjs'
const root=mkdtempSync(path.join(os.tmpdir(),'exhaustion-'))
test.after(()=>rmSync(root,{recursive:true,force:true}))
mkdirSync(path.join(root,'apps/ledger-suit/tests/unit'),{recursive:true});mkdirSync(path.join(root,'apps/ledger-suit/app'),{recursive:true});mkdirSync(path.join(root,'docs/shared'),{recursive:true})
writeFileSync(path.join(root,'apps/ledger-suit/tests/unit/shared-ui-migration.test.mjs'),"readdirSync(directory); assert.deepEqual(actual, [])")
writeFileSync(path.join(root,'docs/shared/ui-ownership-manifest.json'),JSON.stringify({components:[]}))
const check={name:'ledger-shared-ui-tests',status:'fail',failure_class:'verification-product-defect',summary:'ENOENT scandir app/components'}
const snapshot=check=>({packet:{task:{task_id:'BS-SA-SHELL-001'},retry_policy:{max_attempts:5}},executions:Array.from({length:5},(_,i)=>({execution_id:i+1,attempt:i+1,status:'failed',worktree_path:root,metadata:{verification_probe_failures:[check]}}))})
test('all five verifier failures reclaim product slots while preserving ordinals',()=>{const s=snapshot(check),before=JSON.stringify(s),audit=auditAttempts(s);assert.equal(audit.consumed,0);assert.equal(audit.action,'same-attempt-recovery');assert.ok(audit.entries.every(e=>e.classification==='VERIFIER_INFRA'));assert.equal(JSON.stringify(s),before)})
test('missing optional directory is safely provisioned and never deletes contents',()=>{assert.ok(emptyComponentFixture(root,check,true));assert.ok(existsSync(path.join(root,'apps/ledger-suit/app/components')));assert.equal(auditAttempts(snapshot(check)).consumed,0);writeFileSync(path.join(root,'apps/ledger-suit/app/components/Forbidden.vue'),'<template/>');assert.equal(emptyComponentFixture(root,check,true),null);assert.ok(existsSync(path.join(root,'apps/ledger-suit/app/components/Forbidden.vue')));rmSync(path.join(root,'apps/ledger-suit/app/components/Forbidden.vue'))})
test('unknown investigation uses persisted claim dedup across cycles and restart',async()=>{const audit=auditAttempts(snapshot({...check,summary:'unexplained result'}));assert.equal(audit.action,'investigate');let started=0;const persisted=new Set();const health={run_id:'r',task_id:'t',state:'STUCK',operator_action_required:false,worker_alive:false,observed_at:new Date().toISOString()};for(let i=0;i<3;i++)await dispatchRecovery({health,snapshot:{exhaustion_audit:audit},claim:async(run,fp,family)=>{assert.equal(family,'unknown-lifecycle');if(persisted.has(fp))return {claimed:false};persisted.add(fp);return {claimed:true,job:{owner:'Codex'}}},start:async job=>{assert.equal(job.owner,'Codex');started++}});assert.equal(started,1)})
test('legacy assertion summaries cannot authorize product exhaustion or human extension',()=>{const audit=auditAttempts(snapshot({...check,summary:'AssertionError: administration shell active rail missing',name:'shell-accessibility'}));assert.equal(audit.consumed,0);assert.equal(audit.action,'investigate');assert.ok(audit.entries.every(e=>e.classification==='UNKNOWN'))})
test('bare legacy exhaustion never becomes NEEDS_ME and UI includes action detail',()=>{const h=classifyHealth({task:{status:'failed'},recovery:{status:'active',error_code:'retry_budget_exhausted',next_action:'wait-operator'}});assert.equal(h.operator_action_required,false);assert.equal(h.state,'STUCK');assert.match(h.why,/audit/);const ui=readFileSync(new URL('../runner/dot-health.html',import.meta.url),'utf8');for(const key of ['root_cause','failed_check','legitimate_attempts','remaining_product_defect','automatic_repair_blocker','required_authorization'])assert.ok(ui.includes(key))})
