import test from 'node:test'
import assert from 'node:assert/strict'
import {foundationImport as r,reviewedFoundationImportPaths as reviewed} from '../runner/reviewed-foundation-import.mjs'
import {unattendedSensitiveFiles} from '../runner/unattended-publication.mjs'
const paths=Object.keys(r.files)
function fixture(){
 const files=paths.map(file=>({file,object:r.files[file]})),fingerprint='verified-exact-state'
 return {task:{task_id:r.task_id},execution:{execution_id:r.execution_id,parent_sha:r.parent_sha,branch_name:'codex/shop-suit/ss-launch-realtime-001'},verification:{verification_run_id:380,execution_id:335,status:'passed',state_fingerprint:fingerprint,verified_state:{files}},objects:{...r.files},authorizations:[{authorization_id:723,contract_id:17873,authorization_kind:'ordinary',source:'human',authorized_paths:paths,revoked_at:null}],contract:{contract_id:17873,required_paths:paths},projectPaths:['packages','pnpm-lock.yaml'],authority:{authorized:true,task_id:r.task_id,run_id:'shop-run',unattended_queue_authority:true,queue_authority_event:19,draft_source_policy:{version:1,mode:'verified-source-draft-only',task_id:r.task_id,run_id:'shop-run',queue_event:19,execution_id:335,verification_run_id:380,parent_sha:r.parent_sha,state_fingerprint:fingerprint,files,merge:false,deploy:false,hosted_sql:false,ancillary:[files[3]]}}}
}
test('exact current reviewed import permits only its approved files',()=>{const x=fixture();assert.deepEqual(reviewed(x),paths.slice(0,3));assert.deepEqual(unattendedSensitiveFiles(paths,{reviewedOrdinaryPaths:reviewed(x)}),[]);assert.deepEqual(unattendedSensitiveFiles([...paths,'packages/auth/src/session.ts','packages/data-access/src/unreviewed.ts'],{reviewedOrdinaryPaths:reviewed(x)}),['packages/auth/src/session.ts','packages/data-access/src/unreviewed.ts'])})
for(const [name,mutate] of Object.entries({changedHash:x=>x.objects[paths[0]]='changed',verifiedHashDrift:x=>x.verification.verified_state.files[0].object='changed',revoked:x=>x.authorizations[0].revoked_at='now',missingAuthority:x=>x.authorizations=[],wrongAuthority:x=>x.authorizations[0].authorization_id=724,contractDrift:x=>x.contract.contract_id=999,missingScope:x=>x.contract.required_paths=[],parentDrift:x=>x.execution.parent_sha='f'.repeat(40),otherTask:x=>x.task.task_id='other',otherExecution:x=>x.execution.execution_id=336,staleVerification:x=>x.verification.verification_run_id=381,failedVerification:x=>x.verification.status='failed',fingerprintDrift:x=>x.verification.state_fingerprint='changed',revokedQueue:x=>x.authority.authorized=false,staleQueue:x=>x.authority.queue_authority_event=20,allowDeploy:x=>x.authority.draft_source_policy.deploy=true,hostedSQL:x=>x.authority.draft_source_policy.hosted_sql=true,allowMerge:x=>x.authority.draft_source_policy.merge=true,outsideProject:x=>x.projectPaths=['apps/shop-suit'],changedLock:x=>x.objects['pnpm-lock.yaml']='changed'}))test(`fails closed: ${name}`,()=>{const x=fixture();mutate(x);assert.deepEqual(reviewed(x),[]);assert.equal(unattendedSensitiveFiles(paths.slice(0,3),{reviewedOrdinaryPaths:reviewed(x)}).length,3)})
