import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { retryDecision, repairRetryDecision } from '../lib/retry-policy.mjs'
import { getProfile } from '../routing/router.mjs'
import { planSupervisorStep } from '../runner/task-supervisor.mjs'
import { effectiveFailureClass } from '../runner/dot.mjs'
import { runWakeEligibility } from '../runner/selfhealing.mjs'
import { validateVerifierOnlyReacceptance } from '../runner/verifier-only-reacceptance.mjs'
import { publicationStateFingerprint } from '../runner/publication-preflight.mjs'
const policy={policy_id:'shared-foundation-five',max_attempts:5,attempt_profiles:['standard','standard','deep','deep','review']}
const fixture=(physical=3,consumed=3)=>({packet:{task:{task_id:'BS-UI-ZN-BROWSER-001',status:'failed'},retry_policy:policy},workflow_run:{status:'running',completed_tasks:6,max_tasks:9},executions:[{execution_id:294,attempt:physical,status:'failed'}],failures:[{failure_id:234,execution_id:294,failure_class:'verification-product-defect',metadata:{classification:{failure_class:'verification-product-defect'}}}],retry_accounting:{consumed,all_product:true,classifications:[{execution_id:294,classification:'PRODUCT_DEFECT'}]}})
test('Shared safely replaces old three-attempt exhaustion without editing historical models',()=>{const s=fixture();s.executions[0].resolved_retry_policy={policy_id:'foundation-three',max_attempts:3};s.executions[0].model_name='gpt-6-astra';const before=JSON.stringify(s.executions);assert.equal(planSupervisorStep(s).command,'task-retry');assert.equal(JSON.stringify(s.executions),before)})
for(const [completed,profile,model,effort] of [[1,'standard','gpt-6.1-sol','medium'],[2,'deep','gpt-6.1-sol','high'],[3,'deep','gpt-6.1-sol','high'],[4,'review','gpt-6-astra','high']])test(`Shared product slot ${completed+1} resolves exactly`,()=>{const d=retryDecision(policy,completed);assert.equal(d.next_profile,profile);const p=getProfile(profile);assert.deepEqual(p.model_preferences,[model]);assert.equal(p.reasoning_effort,effort)})
test('Shared five genuine product failures stop at human gate',()=>{const s=fixture(5,5);s.exhaustion_audit={all_attempts_audited:true,action:'operator-gate',entries:[]};assert.equal(planSupervisorStep(s).reason,'retry_budget_exhausted');assert.equal(planSupervisorStep(s).kind,'wait');assert.equal(planSupervisorStep(s).next_action,'wait-operator');assert.equal(retryDecision(policy,5).allowed,false)})
test('Physical ordinal five with reclaimed non-product failures still has product slots',()=>{const s=fixture(5,2);assert.equal(planSupervisorStep(s).command,'task-retry');assert.equal(retryDecision(policy,s.retry_accounting.consumed).next_profile,'deep')})
for(const classification of ['VERIFIER_INFRA','CONFIGURATION'])test(`${classification} recovery reuses existing execution before any repair slot`,()=>{const s=fixture(3,1);s.run_publication_authority={authorized:true};s.retry_accounting.classifications[0]={execution_id:294,classification,source:'human'};assert.match(effectiveFailureClass(s,'verification-product-defect'),/^verification-/);assert.equal(planSupervisorStep(s).command,'task-reaccept');assert.equal(planSupervisorStep(s).execution.execution_id,294)})
test('Dot scans exhausted failed Shared runs in the ordinary watchdog cycle',()=>{const runner=readFileSync(new URL('../runner/bs-agent.mjs',import.meta.url),'utf8');const watch=runner.slice(runner.indexOf('function recoveryWatch()'),runner.indexOf('function recoverWorkflowRun()'));assert.match(readFileSync(new URL('../runner/dot-health-inputs.sql',import.meta.url),'utf8'),/control\.run_is_actionable/);assert.ok(watch.indexOf('reconcile_shared_retry_exhaustion')<watch.indexOf('runWakeEligibility'));const s=fixture();assert.equal(runWakeEligibility(s.workflow_run,{status:'resolved',next_action:'retry',error_code:'retry_exhaustion_reconciled'},null,Date.now(),s).eligible,true);assert.equal(runWakeEligibility({...s.workflow_run,maintenance_requested:true},null,null,Date.now(),s).eligible,false)})
test('Exact reviewed selector correction cannot permit product edits or skipped required checks',()=>{const original={base_sha:'base',files:[{file:'apps/ledger-suit/tests/e2e/shared-ui-foundation.spec.ts',object:'old-test'},{file:'packages/ui/src/table.vue',object:'product'}]};const current={...original,files:[{...original.files[0],object:'fixed-selector'},original.files[1]]};current.fingerprint=publicationStateFingerprint(current);const execution={execution_id:294,attempt:3,status:'failed',metadata:{verification_probe_verified_state:original,verification_probe_failures:[{name:'browser'}]}};const probe={ok:true,passed:true,checks:[{name:'browser',required:true,status:'pass'}],verified_state:current};const args={execution,probe,currentState:current,verifierPaths:[original.files[0].file],requiredChecks:['browser']};assert.equal(validateVerifierOnlyReacceptance(args).preserved_attempt,3);assert.throws(()=>validateVerifierOnlyReacceptance({...args,probe:{...probe,checks:[{name:'browser',required:true,status:'skipped'}]}}),/mandatory_check/);const changed={...current,files:[current.files[0],{...original.files[1],object:'changed-product'}]};changed.fingerprint=publicationStateFingerprint(changed);assert.throws(()=>validateVerifierOnlyReacceptance({...args,currentState:changed,probe:{...probe,verified_state:changed}}),/product_source_changed/);assert.throws(()=>validateVerifierOnlyReacceptance({...args,verifierPaths:['packages/ui/src/table.vue']}),/verifier_paths_only/)})

test('Unreviewed earlier failures cannot be declared genuine five-product exhaustion',()=>{const s=fixture(5,5);s.retry_accounting.all_product=false;assert.equal(planSupervisorStep(s).reason,'retry_audit_required');assert.equal(planSupervisorStep(s).kind,'wait')})

test('An already-running final reservation resumes its recorded model and profile without another slot',()=>{const previous={task_id:'BS-UI-ZN-BROWSER-001',attempt:4};const running={task_id:previous.task_id,attempt:5,status:'running',model_profile:'review',model_name:'gpt-6-astra'};const d=repairRetryDecision(policy,previous,{consumed:5},running);assert.equal(d.allowed,true);assert.equal(d.resumed,true);assert.equal(d.next_profile,'review');assert.equal(d.next_attempt,5);assert.throws(()=>repairRetryDecision(policy,previous,{consumed:5},{...running,task_id:'OTHER-TASK-001'}),/same_task_running/);assert.equal(repairRetryDecision(policy,{attempt:5},{consumed:5}).allowed,false)})

test('one reviewed extra survives validation and reaches actual supervisor without changing configured budget',()=>{
 const s=fixture(8,5);s.packet.retry_policy={...policy,one_invocation_extension:{grant_id:42,profile:'review',run_id:'fixture-run'}}
 assert.equal(planSupervisorStep(s).command,'task-retry')
 const result=repairRetryDecision(s.packet.retry_policy,s.executions[0],s.retry_accounting)
 assert.equal(result.next_profile,'review');assert.equal(result.operator_grant_id,42);assert.equal(result.max_attempts,5)
})

test('historical PASS without a bound receipt enters same-execution reverification',()=>{
 const s=fixture();s.packet.task.status='passed';s.executions[0].status='failed';s.verification_runs=[{verification_run_id:77,execution_id:294,status:'passed'}]
 s.publication_execution_eligible=true
 s.verification_results=[{verification_run_id:77,status:'pass',metadata:{required:true}}]
 const result=planSupervisorStep(s)
 assert.equal(result.command,'task-verify');assert.equal(result.reason,'trusted_pass_reverification_required');assert.equal(result.execution.execution_id,294)
})
